.github/workflows/cloudbeat-ci.yml, JUSTFILE, README.md, config/config.go, deploy/k8s/cloudbeat-ds-debug.yaml, deploy/k8s/cloudbeat-ds.yaml, evaluator/evaluator.go, go.mod, go.sum
- fixes: https://github.com/elastic/security-team/issues/3193
=> update findings index

go.mod, go.sum
updating CSP rules version to support the new rules
https://github.com/elastic/security-team/issues/2429
=> Updating csp-version

.github/workflows/cloudbeat-ci.yml
make Integration test work from forks
=> make Integration test work from forks

.github/workflows/cloudbeat-ci.yml, .github/workflows/post-merge.yml, README.md
- Post Merge checks:
- Go report badge
- Go coverage badge
=> Post merge checks

beater/cloudbeat.go
=> manager changes

.github/workflows/cloudbeat-ci.yml
Fixed cloudbeat-ci checkout on integration checks step
=> fix ci checkout integrations

JUSTFILE
Path for the YAML file that contains the deploy instructions was non existing
=> Fixing cloudbeat deploy YAML path

deploy/k8s/kustomize/base/cloudbeat-ds.yml, resources/conditions/kube_lease.go, resources/conditions/kube_lease_test.go
Closes: https://github.com/elastic/security-team/issues/3657
=> 3657 Kube lease remove list

go.mod, go.sum
Bumped version after merging https://github.com/elastic/csp-security-policies/pull/81
=> Bump version for new K8S rules release

resources/fetchers/process_fetcher.go
Enhancing the process id in the fetcher.
Fixes https://github.com/elastic/security-team/issues/3532
Gaps https://github.com/elastic/cloudbeat/issues/76
=> Enhance process id

transformer/common_data_provider.go
Converting our resource ids to UUIDs
Fixes https://github.com/elastic/security-team/issues/3601
=> Convert resource ids to UUIDs

.github/workflows/unit-test.yml, evaluator/opa.go, go.sum, processor/errors.go, resources/fetchers/ecr_factory_test.go, resources/fetchers/ecr_fetcher_test.go, resources/fetchers/eks_factory_test.go, resources/fetchers/elb_factory_test.go, resources/fetchers/elb_fetcher_test.go, resources/fetchers/iam_factory_test.go, resources/fetchers/process_fetcher_test.go, resources/manager/factory_test.go, resources/manager/registry_test.go, transformer/events_creator_test.go
=> Golangci linter step

.github/workflows/unit-test.yml
splitting the CI fix into separate PR:
- this one fixes the Go linter job
=> fix go linter CI

.github/workflows/cloudbeat-ci.yml, .github/workflows/unit-test.yml
- More restrictive steps conditions
=> Integration CI conditions 

.github/workflows/cloudbeat-ci.yml, .github/workflows/unit-test.yml
=> removing explicit checkout 

_meta/config/cloudbeat.common.yml.tmpl, cloudbeat.reference.yml, cloudbeat.yml, config/config.go, config/config_test.go
Fixes https://github.com/elastic/security-team/issues/3866
=> Default period of 4h between cycles

tests/README.md
=> Backport-example-1

tests/README.md
=> Backport-example-2

.github/workflows/cloudbeat-ci.yml, .github/workflows/packaging.yml, .github/workflows/unit-test.yml
Update ci to run on version branches
=> update ci to run on version branches

cmd/version.go
Update version on main to 8.4.0
=> update stack version to 8.4.0

cmd/version.go, go.mod, go.sum, tests/product/tests/test_rules.py, tests/product/tests/tests/file_system/file_system_test_cases.py, tests/product/tests/tests/process/process_test_cases.py
Add component tests for the following rules:
1.2.10
1.2.12
1.2.13
1.2.32
4.1.6
=> Add component tests for new rules

README.md
resolves https://github.com/elastic/security-team/issues/2779
=> Update readme on beta

README.md
Resolves https://github.com/elastic/security-team/issues/3955
=> Instructions for remote_edit_config script

JUSTFILE, tests/commonlib/io_utils.py, tests/commonlib/kubernetes.py, tests/commonlib/utils.py, tests/deploy/mock-pod.yml, tests/product/tests/conftest.py, tests/product/tests/kube_rules.py, tests/product/tests/test_kube_api_rules.py
- adds missing kube-api automated tests
- refactor kube-api rules testing environment 
____
fixes: https://github.com/elastic/security-team/issues/3874
=> Kube api rules atuomated tests

beater/bundle/bundle.go, evaluator/opa.go, transformer/events_creator.go
Fixes https://github.com/elastic/security-team/issues/4168
=> Opa logger rename fields

cmd/version.go, deploy/k8s/standalone-agent.yml
Bump cloudbeat version to 8.3.1
=> 8.3.1-ver-bump

cmd/version.go, deploy/k8s/standalone-agent.yml
=> 8.3.2-ver-bump

config/config.go, config/config_test.go, evaluator/bundle.go, evaluator/bundle_test.go
Adding bundle configuration support per framework (Vanilla and EKS)
=> support bundle loading per FW

cmd/version.go, deploy/k8s/standalone-agent.yml
=> 8.3.3-ver-bump

config/config.go, config/config_test.go
Since I expect this Git task to be a bit complex and I want to be able to offload part of the EKS work to other developers, I am splitting the PR into two.
The first part will be this PR which focuses only on parsing the integration values in Cloudbeat.
The second part will focus on loading the relevant bundle and the AWS credentials - https://github.com/elastic/cloudbeat/pull/258
- Closes: https://github.com/elastic/security-team/issues/2992
=> Adding EKS config values

config/config.go, config/config_test.go, evaluator/bundle_test.go
Adds support to the EKS activated rules field in the data.yaml schema 
____
- closes: https://github.com/elastic/cloudbeat/issues/234
=> EKS activated rules support

_meta/config/cloudbeat.common.yml.tmpl, cloudbeat.reference.yml, cloudbeat.yml
- fixes : https://github.com/elastic/security-team/issues/3041
=> fixing the common.yml.tmpl

.github/workflows/Periodic-CI.yml, .github/workflows/publish-test-results.yml
Fix nightly trigger,adds default fallback - adds
=> Nightly fix & publish time out

.github/workflows/publish-test-results.yml
=> Fix reports url struct

transformer/events_creator.go, transformer/events_creator_test.go
closes https://github.com/elastic/security-team/issues/3786
Before:
After:
=> Add message to our findings

tests/product/tests/data/process/process_test_cases.py, tests/product/tests/test_process_api_server_rules.py, tests/product/tests/test_process_controller_manager_rules.py, tests/product/tests/test_process_etcd_rules.py, tests/product/tests/test_process_kubelet_rules.py, tests/product/tests/test_process_scheduler_rules.py, tests/pylintrc
Adding pylintrc (pylint config file) + fixing the code to pass flake8 with:
```bash
flake8 --ignore=E501,E126,E123 tests/product 
```
____
- Related: https://github.com/elastic/security-team/issues/4297
=> adding pylintrc

evaluator/evaluator.go
=> Add benchmark id field to schema

go.mod, go.sum, resources/fetchers/ecr_factory.go, resources/fetchers/ecr_factory_test.go, resources/fetchers/ecr_fetcher.go, resources/fetchers/ecr_fetcher_test.go, resources/providers/awslib/ecr_public_provider.go
- fixes: https://github.com/elastic/security-team/issues/4035
=> Removing public ecr from ecr fetcher

.mergify.yml, cmd/version.go
Bump main to 8.5 & update mergify 8.4 updates
=> Bump main to 8.5

cmd/version.go
=> 8.3.4-bump

resources/fetchers/kube_fetcher.go, resources/fetchers/kube_provider.go
- Fixes: https://github.com/elastic/cloudbeat/issues/285
=> Fixing_EKS_CIS_5.4.3

.github/ISSUE_TEMPLATE/csp_task.md
Relates:
- https://github.com/elastic/integrations/issues/3642
=> Update GH CSP task template

.ci/scripts/rm-docker.sh, Jenkinsfile
https://github.com/elastic/security-team/issues/4292
example of successful run 
https://internal-ci.elastic.co/blue/organizations/jenkins/cloudbeat%2Fcloudbeat-mbp/detail/PR-335/14/pipeline
DRA publishing seems to work https://artifacts-snapshot.elastic.co/cloudbeat/8.5.0-d3a61940/summary-8.5.0-SNAPSHOT.html
=> DRA job to produce both snapshot & staging artifact by default

_meta/config/cloudbeat.common.yml.tmpl, cloudbeat.reference.yml, cloudbeat.yml, deploy/kustomize/base/config-map.yml, tests/deploy/cloudbeat-pytest.yml, tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml, tests/product/tests/data/file_system/file_system_test_cases.py, tests/product/tests/test_file_system_rules.py
Resolves: https://github.com/elastic/security-team/issues/4484
=> Fix flaky file_system_rules tests with better resource-matching.

tests/commonlib/io_utils.py, tests/deploy/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml, tests/product/tests/data/file_system/file_system_test_cases.py, tests/product/tests/test_file_system_rules.py
Resolves https://github.com/elastic/security-team/issues/4311
=> Fix broken file_system_rules tests.

cmd/version.go
=> 8.4.1-bump

cmd/version.go
=> 8.4.2-bump

config/config_test.go
Related to https://github.com/elastic/security-team/issues/4495
=> chore: add test

.github/workflows/cloudbeat-ci.yml, JUSTFILE, tests/conftest.py, tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-test-configmap.yml, tests/deploy/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml, tests/product/tests/conftest.py, tests/product/tests/parameters.py, tests/product/tests/test_file_system_rules.py, tests/product/tests/test_k8s_objects_rules.py, tests/product/tests/test_process_api_server_rules.py, tests/product/tests/test_process_controller_manager_rules.py, tests/product/tests/test_process_etcd_rules.py, tests/product/tests/test_process_kubelet_rules.py, tests/product/tests/test_process_scheduler_rules.py
Add the range option to tests so they can be split up and run in concurrent parts using a test matrix.
=> Make tests more concurrent.

cmd/version.go
=> version bump - 8.4.3

.mergify.yml, cmd/version.go, justfile
=> Bump main to 8.6

cmd/version.go
=> version bump - 8.4.4

.github/workflows/cloudbeat-ci.yml, justfile, tests/deploy/cloudbeat-pytest.yml, tests/deploy/k8s-cloudbeat-tests/values.yaml
- Increase cloudbeat's cycle duration to 30s
- Add cloudbeat resource limits
- Increase ES resource limit
**Checklist**
=> Optimize test stack resources & cloudbeat cycle duration

.github/CODEOWNERS
update code owners file to include justfile under csp-ops
**Checklist**
=> update code owners file

Dockerfile.debug, README.md, justfile
This PR fixes the debug setup of Cloudbeat.
It updates the readme and the relevant JUST file commands.
=> Fix Cloudbeat debug setup

README.md, justfile
Adds hermit to the main readme section
**Checklist**
=> hermit add to readme

cmd/version.go, justfile
- Version bump - 8.5.0 -> 8.5.1
- Hard code base image version for testing
=> version bump - 8.5.1

go.mod, go.sum
Bumping ⬆️ 
___
- Related: https://github.com/elastic/csp-security-policies/pull/135
=> Update csp-security-policies to v1.2.2

cmd/version.go
=> version bump - 8.5.2

.github/workflows/cloudbeat-ci.yml, justfile, tests/product/tests/data/process/process_test_cases.py
- Fixing the CI issue where our functional tests passed the CI checks where in reality they failed.
- Separating the etcd tests
proof that the CI fix worked:
**Checklist**
=> fix CI false positive functional tests

cmd/version.go
Updates references to the new release 8.5.3.
Merge after the release 8.5.2.
=> [Release] Update version to 8.5.3

go.mod, go.sum
Updated elastic-agent-client to latest version fixing casing in reported unit state
=> Updated elastic-agent-client to v7.0.2-0.20221129150247-15881a8e64ef

scripts/make/generate_notice.py, tests/pylintrc
Restoring default encoding that relay on the env var in order to fix the packaging [Jenkins workflow](https://internal-ci.elastic.co/blue/organizations/jenkins/cloudbeat%2Fcloudbeat-mbp/detail/main/255/pipeline/)
=> Fix Packaging

cmd/version.go
Updates references to the new release 8.5.4.
Merge after the release 8.5.3.
=> [Release] Update version to 8.5.4

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/issue_template.md, .github/workflows/cloudbeat-ci.yml, .github/workflows/unit-test.yml
Running the same testing jobs on post merge creates unneeded test results and adds too much noise to the post merge results.
Removing unnecessary jobs
=> [Cloud Posture] Removing UT and cloudbeat CI from post merge

go.mod, go.sum
Update `libbeat` module to a version that fixes the dynamic log level [issue](https://github.com/elastic/cloudbeat/issues/623)
- https://github.com/elastic/cloudbeat/issues/623
=> chore: update libbeat

.github/workflows/eks-ci.yml
This PR adds execution of EKS functional tests on post-merge
=> Eks post merge ci

deploy/aws/cloudbeat-aws.yml, resources/fetchers/network_fetcher.go, resources/fetchers/network_fetcher_test.go, resources/fetching/fetcher.go, resources/providers/awslib/ec2/ebs_encryption.go, resources/providers/awslib/ec2/mock_client.go, resources/providers/awslib/ec2/mock_elastic_compute.go, resources/providers/awslib/ec2/provider.go, resources/providers/awslib/ec2/provider_test.go, resources/providers/awslib/ec2_metadata_provider.go, resources/providers/awslib/multi_region.go, resources/providers/awslib/multi_region_test.go
add aws cis 2.2.1
Related https://github.com/elastic/csp-security-policies/issues/145
=> Aws cis 2 2 1

resources/fetchers/network_fetcher.go, version/policy.go
1. CSP policies version bump.
2. Fix a bug in the network fetcher.
- Related: https://github.com/elastic/cloudbeat/pull/705
=> CSP policies version bump

.github/workflows/publish-artifacts.yml, deploy/cloudformation/elastic-agent-ec2.yml
Continue PR https://github.com/elastic/cloudbeat/pull/774
Resolves https://github.com/elastic/cloudbeat/issues/698
=> Change trigger for CloudFormation template upload to S3

tests/product/tests/data/aws/aws_s3_test_cases.py
Added functional tests for CIS AWS Rules 2.1.1 - 2.1.3
=> implement tests for AWS Rules 2.1.1-2.1.3

.github/workflows/k8s-ci.yml
```
matrix:
test-target: ['full']
range: ['functional']
```
This PR removes 'full' marker and 'functional' range that are not supported.
=> update k8s workflow

dev-docs/Architecture.md, dev-docs/ELK-Deployment.md, dev-docs/Release.md
Remove private links and fix a duplicate link to staging.found.no
=> Docs: Fix links

deploy/cloudformation/elastic-agent-ec2.yml
Add permission of snapshot deletion to the role Cloudformation attaches to the newly created ec2.
- Related: https://github.com/elastic/cloudbeat/issues/607
=> Cloudformation script to support snapshot deletion

deploy/cloudformation/README.md, deploy/cloudformation/config.go, deploy/cloudformation/dev/modifier.go, deploy/cloudformation/elastic-agent-ec2.yml, deploy/cloudformation/godev.go, deploy/cloudformation/gomain.go
The cloudformation dev script accept a `deploiy/cloudformation/.env` file of the form:
```
STACK_NAME=""
FLEET_URL=""
ENROLLMENT_TOKEN=""
ELASTIC_AGENT_VERSION="" // 8.8.0 | 8.8.0-SNAPSHOT
DEV.KEY_NAME="" // Your EC2 key for SSH
DEV.ALLOW_SSH=bool
DEV.PRE_RELEASE=true // Set to true in order to replace the artifact URL with a pre-release version (BC or snapshot)
DEV.SHA="" // A specific SHA of a pre-release artifact (on SNAPSHOT versions you can leave empty to take the latest)
```
=> CloudFormation script deploy BC

resources/providers/awslib/rds/provider.go
adds pagination by using the output's marker property. 
- fixes https://github.com/elastic/cloudbeat/issues/913
=> Add pagination in RDS provider to describe DB instances

deploy/cloudformation/README.md, deploy/vulnerability/README.md
Document how developers should run vulnerability management flow in two use cases:
1. Using CloudFormation on AWS
2. Locally
- Resolves: https://github.com/elastic/cloudbeat/issues/833
=> Document ways to run vulnerability management

version/version.go
Updates references to the new release 8.7.2.
Merge after the release 8.7.1.
=> [Release] Update version to 8.7.2

catalog-info.yaml
Add a catalog info file for buildkite pipeline defintions.
- Related: https://github.com/elastic/security-team/issues/4708
=> Add a catalog info file

deploy/cloud/README.md, deploy/cloud/main.tf, deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf, deploy/cloud/modules/provision-eks-cluster/main.tf, deploy/cloud/modules/provision-eks-cluster/oidc.tf, deploy/cloud/modules/provision-eks-cluster/security-groups.tf, deploy/cloud/modules/provision-eks-cluster/variables.tf, deploy/cloud/modules/provision-eks-cluster/vpc.tf, deploy/cloud/variables.tf
In this PR when using terraform we now ask for environment name with suggested format
=> Enforce deployment name when using terraform

deploy/cloudformation/config.go, deploy/cloudformation/gomain.go
- Related: https://github.com/elastic/cloudbeat/pull/943
- Related: https://github.com/elastic/cloudbeat/issues/937
=> CloudFormation script: Fix artifact server not being optional

.github/workflows/publish-artifacts.yml
- Use the `paths:` syntax instead of `tj-actions/changed-files`
- Also run on workflow file change
I've played a bit to test the syntax/logic here https://github.com/orestisfl/test-actions
- Related: #596
=> CloudFormation: Use GH actions syntax for conditional upload

.github/workflows/publish-artifacts.yml
- Related: https://github.com/elastic/cloudbeat/issues/596
- Related: https://github.com/elastic/cloudbeat/pull/976#pullrequestreview-1428857342
=> CloudFormation: Remove duplicate s3 upload

README.md, catalog-info.yaml
1. Create a branch filter for running a buildkite pipeline
2. Add a buildkite build badge to the repo.
=> Create a branch filter for running a builkite pipeline

Makefile, bin/hermit.hcl, justfile
=> Fix merge conflicts

README.md, catalog-info.yaml
Reverts elastic/cloudbeat#1002
=> Revert "Create a branch filter for running a builkite pipeline"

tests/product/tests/data/aws/aws_rds_test_cases.py, tests/product/tests/data/aws/aws_s3_test_cases.py
Implement two CIS AWS functional tests:
- 2.1.5 Ensure that S3 Buckets are configured with 'Block public access'
- 2.3.3 Ensure that public access is not given to RDS Instance
Resolves https://github.com/elastic/cloudbeat/issues/963
Resolves https://github.com/elastic/cloudbeat/issues/964
=> Implement CIS AWS functional tests for rules 2.1.5, 2.3.3

.buildkite/pipeline.yml, .buildkite/scripts/package.sh, .ci/scripts/ecr-images.sh, .github/workflows/eks-ci.yml
1. Remove the make command from EKS post-merge CI.
2. Use the same Python binary as before the makefile removal.
Related: 
- https://github.com/elastic/cloudbeat/issues/466
=> Fix makefile leftovers

.ci/scripts/allure-report-summary.sh, .github/workflows/publish-test-results.yml
Adding Allure report summary comment.
[Allure summary comment](https://github.com/oren-zohar/cloudbeat/pull/2#issuecomment-1575515605):
- Fixes: https://github.com/elastic/security-team/issues/5401
=> Allure report summary comment

catalog-info.yaml
Escaping the $ sign as buildkite expects.
- Related: https://github.com/elastic/security-team/issues/4708
=> Format pipeline branch filter the buildkite way

deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf, deploy/cloud/modules/provision-eks-cluster/variables.tf, deploy/test-environments/main.tf
This PR has introduced support for tags in EKS clusters.
=> [Sanity Jobs] Added tags support for eks cluster

flavors/benchmark/aws.go, flavors/benchmark/benchmark.go, flavors/benchmark/benchmark_test.go, flavors/benchmark/eks.go, flavors/benchmark/k8s.go, resources/fetching/factory/aws_factory.go, resources/fetching/factory/eks_factory.go, resources/fetching/factory/k8s_factory.go
- Related: https://github.com/elastic/cloudbeat/pull/1093#discussion_r1245306205
=> Benchmarks: add some missing tests

transformer/events_creator_test.go, transformer/opa_results.json
=> events_creator_test: Fix JSON parse error

.pre-commit-config.yaml, deploy/cloudformation/ec2-types.yml
Make sure the `cfn-python-lint` pre-commit hook check all templates under the CloudFormation folder.
=> Pre-commit hook cfn-python-lint to scan all templates

.github/workflows/test-environment.yml, dev-docs/sanity-workflow.md
Run sanity tests based on a new checkbox
=> Conditionally run sanity tests

.github/workflows/destroy-environment.yml
This pull request (PR) addresses a bug related to an incorrect definition of the "ignore-prefix" parameter. The bug was causing issues in the application due to the parameter being misconfigured or misused.
=> fix inputs params

.github/workflows/unit-test.yml, flavors/benchmark/gcp.go, flavors/posture.go, resources/providers/gcplib/auth/credentials.go, resources/providers/gcplib/auth/credentials_test.go, resources/providers/gcplib/identity/identity_provider.go
As discussed in https://github.com/elastic/cloudbeat/pull/1144#discussion_r1273272366
This also fixes spurious error logs when running a non-GCP benchmark.
- Related: https://github.com/elastic/cloudbeat/pull/1144
=> gcp: NewProvider: Avoid returning nil

resources/fetching/fetchers/aws/logging_fetcher_test.go, resources/fetching/fetchers/aws/network_fetcher_test.go, resources/providers/awslib/ec2/provider_test.go, vulnerability/events_creator_test.go
Some missed locations
- Related: https://github.com/elastic/cloudbeat/pull/1104
=> Use testhelper.NewLogger in remaining tests

resources/fetching/fetcher.go, resources/fetching/fetchers/aws/network_fetcher.go, resources/fetching/fetchers/gcp/assets_fetcher.go
Add the `compute.googleapis.com/Instance` type to the asset fetcher.
- Related: https://github.com/elastic/csp-security-policies/issues/241
=> [CIS GCP] Add compute instance to fetched resources

resources/fetching/fetcher.go, resources/fetching/fetchers/gcp/assets_fetcher.go
1. Add new type to fetching lib
2. Add new asset type to asset fetcher
=> Add data processing type

resources/fetching/fetchers/gcp/assets_fetcher.go
Add Backend and network to the asset list.
- Related: https://github.com/elastic/csp-security-policies/issues/243
=> [CIS GCP] Add assets to fetcher

resources/fetching/fetchers/gcp/assets_fetcher.go, version/policy.go
1. bump csp policies version before the 8.10 release.
2. Add the subnetwork type to the asset fetcher.
=> Bump csp policies version

.github/workflows/k8s-ci.yml
=> skip agent test

version/version.go
Updates references to the new release 8.9.2.
Merge after the release 8.9.1.
=> [Release] Update version to 8.9.2

version/version.go
Fix wrong version number following human error.
=> Fix branch version number

.github/workflows/unit-test.yml, go.mod, go.sum
makes CI tests output a bit more readable 
see https://pkg.go.dev/github.com/IstrateM/gotestsum/pkg/gotestsum#section-readme
=> Use gotestsum in CI

version/policy.go
includes a bug fix for CIS GCP 1.6
https://github.com/elastic/csp-security-policies/releases/tag/v1.5.5
=> bump CIS bundle version

.github/workflows/bump-golang.yml, .github/workflows/cloudbeat-ci.yml, .github/workflows/cloudformation-ci.yml, .github/workflows/cnvm-ci.yml, .github/workflows/destroy-environment.yml, .github/workflows/eks-ci.yml, .github/workflows/k8s-ci.yml, .github/workflows/packaging.yml, .github/workflows/periodic-ci.yml, .github/workflows/publish-cloudformation.yml, .github/workflows/publish-test-results.yml, .github/workflows/test-environment.yml, .github/workflows/unit-test.yml, .github/workflows/weekly-enviroment.yml
Update to [actions/checkout@v4](https://github.com/actions/checkout/releases/tag/v4.0.0)
According to https://github.com/actions/checkout/issues/1448 it might fix the issue we are encountering. Even if it doesn't, no apparent harm from using the latest version.
=> Update to actions/checkout@v4

.github/workflows/eks-ci.yml
This PR implements skipping EKS functional tests in the post-merge execution.
- https://github.com/elastic/cloudbeat/issues/1317
=> skip post-merge eks tests

version/version.go
Updates references to the new release 8.10.1.
Merge after the release 8.10.0.
=> [Release] Update version to 8.10.1 

version/version.go
Update version to 8.10.2 after 8.10.1 was released.
=> update version to 8.10.2

resources/fetching/fetchers/azure/assets_fetcher_test.go
Apply suggestions from https://github.com/elastic/cloudbeat/pull/1310
- Reduce code
- Protect from panics via `Require()`
- Compare objects directly
- Related https://github.com/elastic/cloudbeat/pull/1310
- Related https://github.com/elastic/cloudbeat/issues/1250
=> Azure fetchers: Improve tests

resources/fetching/fetcher.go, resources/fetching/fetchers/azure/assets_fetcher.go, resources/fetching/fetchers/azure/assets_fetcher_test.go, resources/providers/azurelib/inventory/asset.go
In order to implement vault resource evaluations we would like to support this new type
=> Support vault resource

.github/workflows/test-environment.yml, deploy/test-environments/main.tf, deploy/test-environments/variables.tf
Add elastic resource tags in terraform/actions for testing env, and use github actor as project name
https://github.com/moukoublen/cloudbeat/actions/runs/6548187057
- Fixes: https://github.com/elastic/security-team/issues/6644
=> Add elastic resource tags in terraform/actions for testing env

.github/workflows/publish-cloudformation.yml
Fix path of script from https://github.com/elastic/cloudbeat/pull/1427
Backported manually in https://github.com/elastic/cloudbeat/pull/1449
=> CloudFormation CI: Fix script path typo

resources/fetching/fetchers/azure/batch_fetcher.go, resources/fetching/fetchers/azure/batch_fetcher_test.go, resources/providers/azurelib/inventory/mock_service_api.go, resources/providers/azurelib/inventory/provider.go
- Fixes: #1474 
- Related: #1258
=> [8.11] Azure: Send empty batch resources when missing

.github/dependabot.yml
Reduce spam by batching updates on a weekly schedule
=> Dependabot: Run only on Mondays

deploy/eks/simple-cluster.yml
Add common tags to eks simple cluster to align with the elastic restictions
=> add common elastic tags to eks cluster

magefile.go
Signal handling was relevant to cleanups that are not relevant anymore
- https://github.com/elastic/cloudbeat/pull/1405
=> mage: BuildOpaBundle: Clean-up some leftover code

.ci/scripts/update-beats.sh
Make sure config files are updated as well
Closes https://github.com/elastic/cloudbeat/pull/1529
=> bump-beats: Re-generate mage config after update

version/version.go
=> [Release] Bump version to 8.11.1

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/9b932c47cec8
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/6848346937
---
<Actions>
<summary>Update to elastic/beats@9b932c47cec8</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 9b932c47cec8&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p>
<details><summary>Options:</summary>
<br />
<p>Most of Updatecli configuration is done via …
=> [updatecli] Update to elastic/beats@9b932c47cec8

dev-docs/Development.md
Update dev-docs to explicitly mention `hermit` as part of development set up.
=> Add hermit configuration to dev docs

dev-docs/Development.md
Updated dev documentation to be consistent with already existent documentation
=> Update dev docs to refer to already existing hermit docs

.github/workflows/cloudbeat-ci.yml
Bug was fixed on hermit side
See https://github.com/cashapp/hermit/issues/391
=> hermit: Remove bootstrapping workaround

resources/fetching/fetcher.go, resources/fetching/fetchers/azure/batch_fetcher.go, resources/fetching/fetchers/azure/batch_fetcher_test.go, resources/providers/azurelib/inventory/asset.go, security-policies/RULES.md, security-policies/bundle/compliance/cis_azure/rules/cis_5_3_1/data.yaml, security-policies/bundle/compliance/cis_azure/rules/cis_5_3_1/rule.rego, security-policies/bundle/compliance/cis_azure/rules/cis_5_3_1/test.rego, security-policies/bundle/compliance/cis_azure/test_data.rego, security-policies/bundle/compliance/policy/azure/data_adapter.rego
Related: https://github.com/elastic/cloudbeat/issues/1418
(https://github.com/elastic/integrations/pull/8540)
=> CIS Azure 5.3.1 - Ensure Application Insights are Configured

deploy/azure/ARM-for-organization-account.json, deploy/azure/ARM-for-single-account.json
See second commit for diff between files
Working with current snapshot:
- Fixes #1281
=>  Azure: Add ARM for management group deployment 

deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py, deploy/test-environments/fleet_api/src/package_policy.py
update azure integration deployment
=> update azure integration deployment

flavors/benchmark/azure_test.go, go.mod, go.sum, resources/fetching/fetcher.go, resources/fetching/fetchers/azure/insights_batch_fetcher.go, resources/fetching/fetchers/azure/insights_batch_fetcher_test.go, resources/fetching/preset/azure_preset.go, resources/providers/azurelib/inventory/asset.go, resources/providers/azurelib/inventory/mock_provider_api.go, resources/providers/azurelib/inventory/provider.go, resources/providers/azurelib/inventory/provider_test.go, resources/providers/azurelib/mock_provider_api.go, resources/providers/azurelib/provider.go, security-policies/README.md, security-policies/RULES.md, security-policies/bundle/compliance/cis_azure/rules/cis_5_1_2/data.yaml, security-policies/bundle/compliance/cis_azure/rules/cis_5_1_2/rule.rego, security-policies/bundle/compliance/cis_azure/rules/cis_5_1_2/test.rego, security-policies/bundle/compliance/cis_azure/test_data.rego, security-policies/bundle/compliance/policy/azure/data_adapter.rego
This PR introduces a new fetcher that uses the azure `armmonitor` SDK in order to fetch diagnostic settings. 
It also implements the rule `CIS 5.1.3`.
Related: https://github.com/elastic/cloudbeat/issues/1418
=> CIS Azure rule 5.1.2

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b30a5ec82af0
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/7087022258
---
<Actions>
<summary>Update to elastic/beats@b30a5ec82af0</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh b30a5ec82af0&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/7087022258">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@b30a5ec82af0

deploy/azure/ARM-for-organization-account.json
Same as https://github.com/elastic/cloudbeat/pull/1624 for management group deployment
- Continuation of https://github.com/elastic/cloudbeat/pull/1624
- Fixes #1619
=> ARM-for-organization-account: Deduplicate deployment per region

deploy/test-environments/fleet_api/src/api/common_api.py, deploy/test-environments/fleet_api/src/configuration_fleet.py, deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py
After https://github.com/elastic/cloudbeat/pull/1624 this parameters do not exist anymore
=> Azure CI: Delete old parameters

.github/workflows/test-environment.yml, tests/integration/tests/test_sanity_checks.py
Temporary disable Azure steps and CI tests due to workflow errors
=> Temporary disable Azure steps

resources/fetching/fetcher.go, resources/fetching/fetchers/azure/assets_fetcher.go, resources/providers/azurelib/inventory/asset.go
Clean up Azure Classical VMs pull, [they are completely deprecated](https://learn.microsoft.com/en-gb/azure/virtual-machines/classic-vm-deprecation)
- Fixes: https://github.com/elastic/cloudbeat/issues/1654
=> Clean up Azure Classical VMS

flavors/publisher_test.go
Remove flakky test while https://github.com/elastic/cloudbeat/issues/1661 is not solved
- Related: https://github.com/elastic/cloudbeat/issues/1661
=> Comment out flakky test until we fix it

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6759826fc71a
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/7248487160
---
<Actions>
<summary>Update to elastic/beats@6759826fc71a</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 6759826fc71a&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/7248487160">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@6759826fc71a

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/900137649bcc
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/7248487160
---
<Actions>
<summary>Update to elastic/beats@900137649bcc</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 900137649bcc&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/7248487160">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@900137649bcc

security-policies/README.md, security-policies/RULES.md, security-policies/bundle/compliance/cis_azure/rules/cis_6_2/data.yaml, security-policies/bundle/compliance/cis_azure/rules/cis_6_2/rule.rego, security-policies/bundle/compliance/cis_azure/rules/cis_6_2/test.rego, security-policies/bundle/compliance/policy/azure/virtual_machine/network_rules.rego
Implement CIS 6.2
- Part of https://github.com/elastic/cloudbeat/issues/1419
=> Add Azure CIS 6.2

.github/workflows/cnvm-ci.yml
Moves the CNVM CI pipeline post-merge to unblock other PRs
=> Run CNVM-CI post-merge

security-policies/RULES.md, security-policies/bundle/compliance/cis_azure/rules/cis_6_3/data.yaml, security-policies/bundle/compliance/cis_azure/rules/cis_6_3/rule.rego, security-policies/bundle/compliance/cis_azure/rules/cis_6_3/test.rego, security-policies/bundle/compliance/policy/azure/virtual_machine/network_rules.rego
Implement CIS 6.3
- Part of https://github.com/elastic/cloudbeat/issues/1419
=> Add CIS Azure 6.3

security-policies/README.md, security-policies/RULES.md, security-policies/bundle/compliance/cis_azure/rules/cis_6_4/data.yaml, security-policies/bundle/compliance/cis_azure/rules/cis_6_4/rule.rego, security-policies/bundle/compliance/cis_azure/rules/cis_6_4/test.rego
Implement CIS 6.4
- Part of https://github.com/elastic/cloudbeat/issues/1419
=> Add CIS Azure 6.4

.golangci.yaml
Explain rationale behind disabled rules
Related: #1669
=> revive: Split rules in sections and add comments

.github/workflows/test-environment.yml, deploy/test-environments/fleet_api/pyproject.toml, tests/integration/tests/test_sanity_checks.py, tests/integration/tests/test_sanity_telemetry.py, tests/pyproject.toml
=> Comment flaky telemetry test

.golangci.yaml, deploy/cloudformation/gomain.go, evaluator/logger.go, flavors/benchmark/aws_org.go, resources/fetching/registry/registry.go, resources/providers/aws_cis/logging/provider.go, resources/providers/awslib/cloudtrail/provider.go, resources/providers/awslib/ec2/provider.go, resources/providers/awslib/iam/policy.go, resources/providers/awslib/iam/user.go, resources/providers/awslib/rds/provider.go, resources/providers/awslib/rds/provider_test.go, resources/providers/gcplib/inventory/provider.go, resources/utils/testhelper/helper.go
Fixes: https://github.com/elastic/cloudbeat/issues/1651
=> Enable prealloc linter

resources/providers/gcplib/inventory/asset.go
On startup time cloudbeat is trying to fetch a non existent asset type `monitoring.googleapis.com/LogMetric`, causing the following error:
```
[elastic_agent.cloudbeat][error] Error fetching GCP Asset: rpc error: code = InvalidArgument desc = No IAM_POLICY found that matches asset type monitoring.googleapis.com/LogMetric for consumer project: 377971016637. For a list of supported content types and asset types, see https://cloud.google.com/asset-inventory/docs/supported-asset-types
error details: name = BadRequest field = asset_types desc = No IAM_POLICY found that matches asset type monitoring.googleapis.com/LogMetric for consumer project: 377971016637. For a list of supported content types and asset types, see https://cloud.google.com/asset-inventory/docs/supported-asset-types …
```
=> Fix GCP LogMetric asset

go.mod, go.sum, resources/fetching/fetchers/azure/assets_enricher_storage_account.go, resources/fetching/fetchers/azure/assets_enricher_storage_account_test.go, resources/fetching/fetchers/azure/assets_enrincher_vm_nsg.go, resources/fetching/fetchers/azure/assets_enrincher_vm_nsg_test.go, resources/fetching/fetchers/azure/assets_fetcher_test.go, resources/providers/azurelib/inventory/asset.go, resources/providers/azurelib/inventory/mock_provider_api.go, resources/providers/azurelib/inventory/provider.go, resources/providers/azurelib/inventory/storage.go, resources/providers/azurelib/inventory/storage_test.go, resources/providers/azurelib/mock_provider_api.go, resources/providers/azurelib/provider.go, resources/utils/maps/maps.go, security-policies/README.md, security-policies/RULES.md, security-policies/bundle/compliance/cis_azure/rules/cis_3_11/data.yaml, security-policies/bundle/compliance/cis_azure/rules/cis_3_11/rule.rego, security-policies/bundle/compliance/cis_azure/rules/cis_3_11/test.rego
Rule: Ensure Soft Delete is Enabled for Azure Containers and Blob Storage
Storage Account enriched extended by fetching blob service for each storage account (one request per storage account).
Blob Service is added at the `extension` field of each storage resource on which the rego rules are based.
Fixes: https://github.com/elastic/cloudbeat/issues/1416
=> [CIS] Azure 3.11

resources/fetching/fetchers/k8s/file_system_fetcher.go
Enrich error log
- Related: https://github.com/elastic/cloudbeat/issues/1753
=> Add path to times stat operation non permitted error

.github/workflows/azure-ci.yml, deploy/azure/cloudbeat-azure.yml, tests/configuration.py, tests/product/tests/data/azure/azure_app_service_test_cases.py, tests/product/tests/data/azure/azure_database_service_test_cases.py, tests/product/tests/data/azure/azure_identity_access_management_test_cases.py, tests/product/tests/data/azure/azure_key_vault_test_cases.py, tests/product/tests/data/azure/azure_logging_and_monitoring_test_cases.py, tests/product/tests/data/azure/azure_networking_test_cases.py, tests/product/tests/data/azure/azure_storage_account_test_cases.py, tests/product/tests/data/azure/azure_virtual_machine_test_cases.py, tests/product/tests/data/azure_test_case.py, tests/product/tests/test_azure_app_service_rules.py, tests/product/tests/test_azure_database_service_rules.py, tests/product/tests/test_azure_identity_access_management_rules.py, tests/product/tests/test_azure_key_vault_rules.py, tests/product/tests/test_azure_logging_and_monitoring_rules.py, tests/product/tests/test_azure_networking_rules.py, tests/product/tests/test_azure_storage_account_rules.py, tests/product/tests/test_azure_virtual_machine_rules.py
Adding implementation for Azure rule tests for the CI workflows
- Fixes: https://github.com/elastic/cloudbeat/issues/1548
=> Implementing Azure CI rule tests

.github/workflows/test-environment.yml, .github/workflows/weekly-serverless.yml
GCP naming conventions error on capital letters.
This PR changes the weekly environment name to lowercase.
=> Weekly env lower case

.github/workflows/k8s-ci.yml
Skipping Post-merge K8s CI until https://github.com/elastic/cloudbeat/issues/1638 is resolved
=> Skip K8s CI

security-policies/README.md, security-policies/RULES.md, security-policies/bundle/compliance/cis_azure/rules/cis_4_1_6/data.yaml, security-policies/bundle/compliance/cis_azure/rules/cis_4_1_6/rule.rego, security-policies/bundle/compliance/cis_azure/rules/cis_4_1_6/test.rego
Implement CIS Azure 4.1.6
_Beware: most of servers have 0 retention period by default, therefore it passes. You need to edit the auditing policy to make it fail_
When configured with 71 days (less than 91 days)
When configured with 91 days:
- Related https://github.com/elastic/cloudbeat/issues/1417
=> CIS Azure 4.1.6

.github/dependabot.yml
=> Remove duplicate schedule from dependabot.yml

vulnerability/replicator.go, vulnerability/scanner.go, vulnerability/verifier.go, vulnerability/verifier_test.go, vulnerability/worker_test.go
adds `snapshotId` and `instanceId` logs to CNVM scan
=> add cnvm id logs

resources/providers/awslib/account_provider.go, resources/providers/awslib/account_provider_test.go, resources/providers/awslib/iam/policy.go, resources/providers/azurelib/inventory/postgresql_provider.go, resources/providers/azurelib/inventory/resource_graph_provider.go, resources/providers/azurelib/inventory/sql_server_provider.go, resources/providers/azurelib/inventory/storage_provider.go, resources/utils/pointers/pointers.go, resources/utils/pointers/pointers_test.go, resources/utils/ptrs/ptrs_test.go, resources/utils/strings/strings_test.go
In a previous PR the `ptrs.Deref` was introduced, which is a generic version of the string specific `strings.Dereference`. This PR refactors the usage of strings to the generic ptrs
=> Move strings.Dereference to ptrs.Deref

version/version.go
=> [Release] Bump version to 8.12.1

dev-docs/Cloudbeat-Deployment.md
Add dev doc for deploying Fleet enrolled Elastic Agent in a container with custom cloudbeat binary (and optionally custom integration)
=> Add dev doc for deploying Fleet enrolled Elastic Agent with custom binaries

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/cf731e633992
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/7692369082
---
<Actions>
<summary>Update to elastic/beats@cf731e633992</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh cf731e633992&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/7692369082">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@cf731e633992

.github/workflows/cloudbeat-ci.yml, .github/workflows/eks-ci.yml, .github/workflows/k8s-ci.yml, tests/test_environments/sa-agent-pytest.yml
=> Update ci docker images

tests/integration/tests/test_sanity_telemetry.py
Reenabling package policy id check on telemetry sanity test
=> [Sanity Tests] [Telemetry] Re-enable package policy id check

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5e431f32119e
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/7780773374
---
<Actions>
<summary>Update to elastic/beats@5e431f32119e</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 5e431f32119e&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/7780773374">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@5e431f32119e

.github/workflows/packaging.yml
to fix the build in https://github.com/elastic/cloudbeat/actions/runs/7797767231?pr=1906 adding a cleanup step to the `packaging` github workflow
- similar change for other workflows https://github.com/elastic/cloudbeat/pull/1156
=> add cleanup step for packaging

.github/workflows/packaging.yml
backport of:
- https://github.com/elastic/cloudbeat/pull/1908
into 8.12
=> [Cloud Security] add cleanup step for packaging (#1908)

internal/flavors/publisher.go
Logging non ECS fields should be capitalized.
=> Publisher event.Count log field

deploy/cloud/modules/serverless/main.tf
Align with:
> Serverless project-api breaking change: resetting "internal" user credentials
=> [Terraform] Update Serverless reset-creds address

.github/workflows/unit-test.yml
=> [8.12] Github Action: use golangci-lint binary from hermit

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d3cac73cfca8
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/7868330687
---
<Actions>
<summary>Update to elastic/beats@d3cac73cfca8</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh d3cac73cfca8&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/7868330687">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@d3cac73cfca8

.github/workflows/bump-version.yml, scripts/bump_cloudbeat.sh, scripts/bump_integration.sh
2 things missing from https://github.com/elastic/cloudbeat/pull/1934
- `awk` command was working locally but not on GH. changed and verified it works on CI too 
- used wrong release branch when creating a PR
=> workflow bump fixes

internal/resources/fetching/fetchers/azure/assets_enricher_sql_server.go, internal/resources/fetching/fetchers/azure/assets_enricher_sql_server_test.go, internal/resources/fetching/fetchers/azure/assets_fetcher_test.go, internal/resources/providers/azurelib/inventory/asset.go, internal/resources/providers/azurelib/inventory/mock_sql_provider_api.go, internal/resources/providers/azurelib/inventory/sql_server_provider.go, internal/resources/providers/azurelib/inventory/sql_server_provider_test.go, internal/resources/providers/azurelib/mock_provider_api.go, security-policies/bundle/compliance/cis_azure/rules/cis_4_1_2/rule.rego, security-policies/bundle/compliance/cis_azure/rules/cis_4_1_2/test.rego
Fix rule 4.1.2 Ensure no Azure SQL Databases allow ingress from 0.0.0.0/0 (ANY IP)
Fixes: https://github.com/elastic/cloudbeat/issues/1472
=> Fix rule CIS Azure rule 4.1.2 

version/version.go
Updates references to the new release 8.12.3.
Merge after the release 8.12.2.
=> [Release] Update version to 8.12.3

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/a5454dba2b5e
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/8136966794
---
<Actions>
<summary>Update to elastic/beats@2b64b95f2d42</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 2b64b95f2d42&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/8136966794">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@a5454dba2b5e

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/7b24d45f66f9
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/8228906379
---
<Actions>
<summary>Update to elastic/beats@7b24d45f66f9</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 7b24d45f66f9&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/8228906379">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@7b24d45f66f9

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/201933e627bb
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/8322557493
---
<Actions>
<summary>Update to elastic/beats@201933e627bb</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 201933e627bb&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/8322557493">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@201933e627bb

version/version.go
=> [Release] Bump version to 8.13.1

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f871b5c5f76b
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/8505062349
---
<Actions>
<summary>Update to elastic/beats@f871b5c5f76b</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh f871b5c5f76b&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/8505062349">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@f871b5c5f76b

.github/workflows/rerun-flaky-workflows.yml
This PR updates the Rerun Flaky Workflow to monitor the `Tests` flow as well.
=> Update the rerun flaky workflow to also monitor the Tests flow.

.github/workflows/ci.yml
=> ci fix: use pr merge commit as base for lint and unittest

internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go, internal/resources/fetching/fetchers/gcp/log_sink_fetcher_test.go, internal/resources/fetching/fetchers/gcp/monitoring_fetcher_test.go, internal/resources/fetching/fetchers/gcp/policies_fetcher_test.go, internal/resources/fetching/fetchers/gcp/service_usage_fetcher_test.go
https://github.com/elastic/cloudbeat/pull/2085 broke main due to changes that weren't accounted for in tests files
=> fix GCP fetchers tests

version/version.go
=> [Release] Bump version to 8.13.3

version/version.go
Updates docs versions to 8.13.2.
Merge before the final Release build.
=> docs: update docs versions 8.13.2

version/version.go
Reverts elastic/cloudbeat#2105
=> Revert "docs: update docs versions 8.13.2"

.github/workflows/ci.yml
=> Omit hermit action in merge code

.github/workflows/ci.yml
Fix Test/Lint step. Will merge while it fails (due to `pull_quest_target` workflow runs from target branch).
=> fix lint step

.github/workflows/test-gcp-dm.yml
=> fix workflow

.github/workflows/test-gcp-dm.yml
=> Fix broken dm workflow

.github/workflows/ci.yml
=> Increase CNVM timeout

.pre-commit-config.yaml
Use local `golanci-lint` in `pre-commit` hook to avoid maintaining two releases (hermit and pre-commit config) and also redownloading through both hermit and pre-commit.
=> [pre-commit] use local (hermit) golangci-lint binary

internal/resources/fetching/fetchers/gcp/assets_fetcher.go, internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go
A quickfix for https://github.com/elastic/cloudbeat/pull/2126
Proof:
=> Fix host info for GCP Compute Instances

version/version.go
Updates references to the new release 8.13.4.
Merge after the release 8.13.3.
=> [Release] Update version to 8.13.4

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ff424ea42bbd
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/8965316311
---
<Actions>
<summary>Update to elastic/beats@ff424ea42bbd</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh ff424ea42bbd&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/8965316311">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@ff424ea42bbd

.buildkite/scripts/package.sh
Follow up on https://github.com/elastic/cloudbeat/pull/2181
Make mage verbose to see if more context is printed
=> Make mage package verbose

.pre-commit-config.yaml
See https://github.com/aws-cloudformation/cfn-lint/issues/3219
=> pre-commit: Fix cfn-lint version

.github/workflows/publish-cloudformation.yml
Run "publish cloudformation" workflow when the cloudbeat version changes (e.g. from `8.14.0` to `8.15.0`) in order to deploy the yml files with the new version in filename / URL.
=> Publish cloudformation when version changes

tests/poetry.lock, tests/pyproject.toml
Reverts elastic/cloudbeat#2220
=> Revert "Bump requests from 2.31.0 to 2.32.0 in /tests"

version/version.go
Updates references to the new release 8.14.1.
I had to create it manually since it was not auto-created by @elasticmachine
=> [Release] Update version to 8.14.1

internal/inventory/asset.go, internal/inventory/awsfetcher/fetcher_ec2_instance.go, internal/inventory/awsfetcher/fetcher_ec2_instance_test.go, internal/inventory/awsfetcher/fetcher_networking.go, internal/inventory/inventory_test.go
Surface extra details for Asset Inventory.
Towards https://github.com/elastic/security-team/issues/9088
- ~~I have added the necessary README/documentation (if appropriate)~~
No
=> Asset Inventory Networking information improvements

.mergify.yml, deploy/azure/ARM-for-organization-account.dev.json, deploy/azure/ARM-for-organization-account.json, deploy/azure/ARM-for-single-account.dev.json, deploy/azure/ARM-for-single-account.json, version/version.go
Bump cloudbeat version - `8.16.0`
=> Bump cloudbeat version

deploy/azure/ARM-for-organization-account.json, deploy/azure/ARM-for-single-account.json
Release cloudbeat version - `8.15.0`
=> Release cloudbeat version

scripts/bump_integration.sh
=> Fix `scripts/bump_integration.sh` for direct-keys

version/version.go
Updates references to the new release 8.15.1.
=> [Release] Update version to 8.15.1

go.mod, go.sum
Bump beats to include the latest changes on magefiles to speed up package/dra time.
=> Bump beats

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/07fb76e4475a
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/10448771743
---
<Actions>
<summary>Update to elastic/beats@07fb76e4475a</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 07fb76e4475a&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/10448771743">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@07fb76e4475a

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/af33fad4d50b
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/10555205040
---
<Actions>
<summary>Update to elastic/beats@af33fad4d50b</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh af33fad4d50b&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/10555205040">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] Update to elastic/beats@af33fad4d50b

.github/workflows/cdr-infra.yml
This PR fixes the run name for the `Create Environment with Cloud Logs` workflow.
=> Fix workflow run-name

deploy/azure/ARM-for-organization-account.dev.json, deploy/azure/ARM-for-organization-account.json, deploy/azure/ARM-for-single-account.dev.json, deploy/azure/ARM-for-single-account.json, version/version.go
=> Bump version 9.0.0

tests/integrations_setup/install_agentless_integrations.py
This fixes `install_agentless_integrations.py` after changes have been made to package generation.
See https://github.com/elastic/cloudbeat/actions/runs/10793698071/job/29936235171#step:45:1
=> [Agentless][Tests] Fix environment creation

.github/workflows/arm-template-lint.yml, .github/workflows/ci-pull_request.yml, .github/workflows/ci.yml, .github/workflows/cloudformation-ci.yml, .github/workflows/eks-ci.yml, .github/workflows/packaging.yml, .github/workflows/unit-test.yml
=> Add missing workflows in 8.x

go.mod, go.sum
Run `go get -u ${module}` for each module in `go.mod`.
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/10879056882
---
<Actions>
<action id="1258252833bbd57dcf58149aa20ef85caee263b94a58c9cc417c7e5e5d9b1be5">
<h3>Update Golang Mod Dependencies</h3>
<details id="695073cb6649c0a436759ea78c82d167625811577eab63269ccd8a19701e9422">
<summary>Update golang mod dependencies</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-mods.sh&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/10879056882">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p>
<details><summary>Options:</summary>
<br />
<p>Most of …
=> [updatecli] Update golang mod dependencies

catalog-info.yaml
=> fix buildkite settings to include 8.x branch

.github/actions/docker-images/action.yml
Reverts elastic/cloudbeat#2562
=> Revert "fix gh artifacts upload for docker images"

.mergify.yml
=> Add backport-v8.16.0 label to main apart from 8.x

tests/integrations_setup/install_aws_asset_inventory_integration.py
Update deployment script variables to follow changes in Asset Inventory integration (<https://github.com/elastic/integrations/pull/11481>)
Related PR: https://github.com/elastic/integrations/pull/11481
=> [Asset Inventory][AWS][CI] Update AWS Asset Inventory variable names

tests/integrations_setup/install_azure_asset_inventory_integration.py
Update deployment script variables to follow changes in Asset Inventory integration (<https://github.com/elastic/integrations/pull/11481>)
Related PR: https://github.com/elastic/integrations/pull/11481
=> [Asset Inventory][Azure][CI] Update Azure variable names

deploy/test-environments/variables.tf
This PR updates the deployment template for the ELK stack.
=> Update stack deployment template

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/96968c93d761
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/11817426439
---
<Actions>
<summary>Update to elastic/beats@96968c93d761</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 96968c93d761&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/11817426439">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] 8.16 - Update to elastic/beats@96968c93d761

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f17e0828f1de
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/11887438460
---
<Actions>
<summary>Update to elastic/beats@f17e0828f1de</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh f17e0828f1de&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/11887438460">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] 8.16 - Update to elastic/beats@f17e0828f1de

.github/workflows/test-environment.yml
This fixes the Create Security environment workflow always creating Serverless environments.
=> Fix ESS deployments created with Serverless

tests/fleet_api/agent_policy_api.py, tests/fleet_api/base_call_api.py, tests/fleet_api/common_api.py, tests/fleet_api/package_policy_api.py
This PR fixes the handling of the Fleet API response for version 8.17.
=> Fix handling of Fleet API response

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/633e6f687076
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/12114336719
---
<Actions>
<summary>Update to elastic/beats@633e6f687076</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 633e6f687076&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/12114336719">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] 8.17 - Update to elastic/beats@633e6f687076

.buildkite/scripts/generate_notice.py
Overwrite notice to github.com/gocsaf/csaf/v3
=> Overwrite notice to github.com/gocsaf/csaf/v3

cloudbeat.reference.yml, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/9ea9d467d5a5
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/12347617142
---
<Actions>
<summary>Update to elastic/beats@9ea9d467d5a5</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 9ea9d467d5a5&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/12347617142">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] 8.17 - Update to elastic/beats@9ea9d467d5a5

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/93b018a83621
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/12347617142
---
<Actions>
<summary>Update to elastic/beats@93b018a83621</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 93b018a83621&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/12347617142">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] main - Update to elastic/beats@93b018a83621

.github/workflows/publish-cloudformation.yml, version/version.go
Adding the `workflow_dispatch` trigger.
=> downgrade version

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e9a656591cf6
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/12543196877
---
<Actions>
<summary>Update to elastic/beats@e9a656591cf6</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh e9a656591cf6&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/12543196877">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] 8.17 - Update to elastic/beats@e9a656591cf6

tests/Dockerfile, tests/pyproject.toml
Syncing branches to run fetcher
=> (Sync a branch with main) Fix poetry export

.github/actions/hermit/action.yml
Install poetry export on hermit init env to solve https://github.com/elastic/cloudbeat/actions/runs/12635173910/job/35204634398#logs
=> Install poetry export on hermit init env

go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/424070e87d83
Generated automatically with https://github.com/elastic/cloudbeat/actions/runs/12742238762
---
<Actions>
<summary>Update to elastic/beats@424070e87d83</summary>
<p>ran shell command &#34;.ci/updatecli/scripts/update-beats.sh 424070e87d83&#34;</p>
</details>
<a href="https://github.com/elastic/cloudbeat/actions/runs/12742238762">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p> …
=> [updatecli] 8.17 - Update to elastic/beats@424070e87d83

.github/workflows/eks-ci.yml
This PR updates the EKS CI upload action to use distinct names for the uploaded artifacts.
[EKS CI run](https://github.com/elastic/cloudbeat/actions/runs/12888591569)
- https://github.com/elastic/cloudbeat/pull/2935
=> Fix EKS ci

version/version.go
Updates references to the new release 8.17.2
Merge after the release 8.17.1
=> [Release] Update version to 8.17.2

.github/workflows/bump-version.yml
=> [Bump workflow] Add condition for integration version bumping

.mergify.yml
=> [mergify] add 8.18 label to main

.github/workflows/ci.yml, tests/product/tests/data/azure_asset_inventory/test_cases.py
fix assets inventory CI being skipped
thanks to @gurevichdmitry for spotting the issues
=> Fix skipped assets inventory CI 

.github/workflows/publish-cloudformation.yml
=> Publish cloudformation from 8.x branch

version/version.go
=> Bump 8.18.1

version/version.go
=> Bump 9.0.1

scripts/publish_cft.sh
=> CFT upload: use minor patch version

.github/workflows/test-runner.yml
Since the 8.x branch, which was used as the `main` branch for version 8, no longer exists, this PR updates the workflow to use the latest 8.19 version.
=> Update test runner workflow to support 8.19 branch

.github/workflows/sync-internal-cloudbeat-version.yml
=> Disable cloudbeat version sync workflow

internal/inventory/asset.go, internal/inventory/gcpfetcher/fetcher_assets.go, scripts/update_assets_md/main.go
Rename Type to SubType and Category to Type
- Related https://github.com/elastic/security-team/issues/12549
=> [Asset Discovery] Rename Type to SubType and Category to Type

tests/product/tests/test_aws_asset_inventory.py, tests/product/tests/test_azure_asset_inventory.py, tests/product/tests/test_gcp_asset_inventory.py
Fix `type_` test in asset inventory tests
=> Fix `type_` test in asset inventory tests

scripts/publish_cft.sh
Align asset inventory cloud formation S3 object name with CSPM naming convention
https://github.com/elastic/cloudbeat/pull/3330
https://github.com/elastic/security-team/issues/12732
=> [Cloud Security] Align asset inventory cloud formation S3 object name with CSPM naming convention

tests/product/tests/test_aws_asset_inventory.py, tests/product/tests/test_azure_asset_inventory.py, tests/product/tests/test_gcp_asset_inventory.py
Fix raw check on asset inventory tests
Working tests
=> [Asset Discovery] Fix raw check on asset inventory tests

.buildkite/pipeline.yml, .buildkite/scripts/package.sh, .buildkite/scripts/publish.sh
Reverts elastic/cloudbeat#3350
=> Revert "[9.0](backport #3347) DRA: separate arm64"

.github/workflows/test-runner.yml
=> Update Test Runner workflow

deploy/cloudformation/elastic-agent-ec2-cspm.yml
Only used for organization on-boarding
Fixes #2433
=> Remove cloudbeat-root from single-account cspm

.golangci.yaml, NOTICE.txt, go.mod, go.sum, internal/dataprovider/providers/common/data_provider.go, internal/evaluator/opa.go, internal/inventory/asset.go, internal/inventory/azurefetcher/fetcher_resource_graph.go, internal/inventory/gcpfetcher/fetcher_assets.go, internal/resources/fetching/fetchers/azure/assets_enrincher_virtual_machine.go, internal/resources/fetching/fetchers/k8s/process_fetcher_test.go
Project is unmaintained:
https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc
The go-viber fork is the most-used alternative that we already import indirectly: https://github.com/go-viper/mapstructure
=> Switch from mitchellh/mapstructure to go-viper/mapstructure

internal/resources/providers/awslib/kms/kms.go, internal/resources/providers/awslib/kms/provider.go
Switch to "All Regions" selector for kms provider. Using the "Current Region" selector, a call to IMDS happens, and it hangs on agentless. 
Plus, with that fix, we scan KMS from all regions.
Error log:
```json
{"log.level":"error","@timestamp":"2025-07-30T12:11:20.122+0300","log.logger":"aws","log.origin":{"function":"github.com/elastic/cloudbeat/internal/resources/providers/awslib.(*currentRegionSelector).Regions","file.name":"awslib/current_region_selector.go","file.line":42},"message":"Failed getting current region: operation error ec2imds: GetInstanceIdentityDocument, canceled, context deadline exceeded","service.name":"cloudbeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2025-07-30T12:11:20.122+0300","log.logger":"aws","log.origin":{"function":"github.com/elastic/cloud …
```
=> [aws]: switch to all region selector for kms provider

deploy/asset-inventory-arm/ARM-for-organization-account.dev.json, deploy/asset-inventory-arm/ARM-for-organization-account.json, deploy/asset-inventory-arm/ARM-for-single-account.dev.json, deploy/asset-inventory-arm/ARM-for-single-account.json, deploy/asset-inventory-arm/generate_dev_template.py, deploy/azure/ARM-for-organization-account.dev.json, deploy/azure/ARM-for-organization-account.json, deploy/azure/ARM-for-single-account.dev.json, deploy/azure/ARM-for-single-account.json, deploy/azure/generate_dev_template.py
We would like to make sure that the correct templates are being pulled based on the branch.
=> Template version adjustment
