- deploy/k8s/cloudbeat-ds-debug.yml
- tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yaml
Cloudbeat debug deployment YAML had incorrect permissions to perform Kubernetes queries and because of that `kube-api` wasn't running.
I've added the required permissions and roles in order for it to perform the expected tasks.
Fixes https://github.com/elastic/security-team/issues/3421
> Granting cloudbeat permissions for Kubernetes resources

- resources/fetchers/kube_factory.go
- resources/fetchers/kube_fetcher.go
- resources/fetchers/kube_provider.go
- resources/fetchers/process_fetcher.go
**what this PR do**
- adds more fetchers logs
- set kube-api interval to 30s (hard-coded)
> Kube Fetcher logs + set Interval

- resources/fetchers/file_system_fetcher.go
Due to the gap https://github.com/elastic/cloudbeat/issues/73, decided to have the `path` without `creation date`.
As discussed with @eyalkraft and @tehilashn this means that this PR isn't interested in the physical file, but only in its path for uniqueness. 
I shall note that the path is mounted to the pod and on the host machine the location may be different.
Fixes https://github.com/elastic/security-team/issues/3599
Gaps https://github.com/elastic/cloudbeat/issues/73
Gaps https://github.com/elastic/cloudbeat/issues/78
> File fetcher id change

- .ci/scripts/rm-docker.sh
Pass the `--version` option to the release-manager container, it is
becoming required to ensure that teams version bumps do not need to wait
for the version bump within the docker image.
> Pass version to rm container

- beater/cloudbeat.go
- config/config.go
- config/config_test.go
- config/updates.go
The `dataYaml` var specifies which CIS rules are "active", hence defining the scope of work to be done by the beat.
> Consume dataYaml in config, add config testing

- transformer/common_data_provider.go
- transformer/events_creator_test.go
- transformer/transformer.go
Switched to using libbeat internal utils in order to resolve the node name.
TODO: Should we continue if the initialization of the common data layer has failed?
If yes, then what should we do for the ids and other future data that has not been collected.
How would we in the current state indicate that there is an error (assuming that nobody would look in the logs since everything will work and we cannot understand from the ids that there are problems)?
Fixes https://github.com/elastic/cloudbeat/issues/83
> Common data provider node name resolution

- _meta/config/cloudbeat.common.yml.tmpl
- cloudbeat.reference.yml
- cloudbeat.yml
- deploy/k8s/cloudbeat-ds-debug.yml
- deploy/k8s/kustomize/base/cloudbeat-ds.yml
- go.mod
- go.sum
- tests/deploy/cloudbeat-pytest.yml
- tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
Correcting the fetching of kube contoller manager process
Bumping csp policies version
```json
{
"bundles": {
"test": {}
},
"decision_id": "472a31dd-eaa9-44c0-80be-685a05d1978d",
"input": {
"resource": {
"command": "kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-cidr=10.244.0.0/16 --cluster-name=kind-mono --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --controllers=*,bootstrapsigner,tokencleaner --enable-hostpath-provisioner=true --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=true --port=0 …
```
> Fetch kube controller manager process

- config/config.go
- config/config_test.go
Incoming config updates with slices smaller than the current slice didn't resize the current slice, resulting in undesirable values in the tail of the slice.
> Fix bug in Config.Update

- JUSTFILE
- tests/commonlib/io_utils.py
- tests/commonlib/kubernetes.py
- tests/product/tests/test_process_api_server_rules.py
- tests/product/tests/test_process_controller_manager_rules.py
- tests/product/tests/test_process_etcd_rules.py
- tests/product/tests/test_process_kubelet_rules.py
- tests/product/tests/test_process_scheduler_rules.py
- tests/product/tests/tests/process/process_test_cases.py
Enhancing the tests framework to automatically evaluate process rules
Fixes https://github.com/elastic/cloudbeat/issues/157
> Adding capability of running automated process rules tests

- .ci/scripts/package.sh
- .ci/scripts/rm-docker.sh
- Jenkinsfile
- Makefile
Update ci to run staging builds.
Added drop down list to enable invoking manual Staging build("Release candidates") via an option in cloudbeat's jenkins job
https://internal-ci.elastic.co/job/cloudbeat/job/cloudbeat-mbp/
> Update CI to support producing release candidate builds(aka "Staging")

- beater/cloudbeat.go
- beater/cloudbeat_test.go
- config/config.go
- config/config_test.go
The reconfiguration logic makes cloudbeat align with the CIS rules enabled/disabled by the user.
Prior to this change, the "default" behavior would kick of and send findings for _all_ CIS rules to the index, before the Fleet server could tell it which findings to send. This is undesirable as it pollutes the index with unwanted findings.
> Make cloudbeat wait for initial reconfiguration from Fleet server.

- JUSTFILE
- evaluator/opa.go
- tests/README.md
- tests/commonlib/kubernetes.py
- tests/commonlib/utils.py
- tests/product/tests/conftest.py
- tests/product/tests/kube_rules.py
- tests/product/tests/test_kube_api_rules.py
- tests/product/tests/test_process_api_server_rules.py
- tests/product/tests/test_process_controller_manager_rules.py
- tests/product/tests/test_process_etcd_rules.py
- tests/product/tests/test_process_kubelet_rules.py
- tests/product/tests/test_process_scheduler_rules.py
- tests/product/tests/test_rules.py
- tests/product/tests/tests/file_system/file_system_test_cases.py
- tests/product/tests/tests/process/process_test_cases.py
- tests/pyproject.toml
Building on the great work done by multiple contributors to these tests, this change includes:
1. #### Fix broken tests
Except for the ones [commented out here](https://github.com/elastic/cloudbeat/blob/a558c5cd79e91ee5b54527269cb688fff521963d/tests/product/tests/tests/process/process_test_cases.py#L1307), which need further investigation. The disabled test cases fail and break the cluster, preventing any test cases thereafter to run correctly.
2. #### A single command to run all test targets in succession
```
just run-test-targets
```
For each test target, cleanup and recreate the cluster, run the test target, and collect its logs and reports.
3. #### New separate markers for each test target
Described in more detail [here](https://github.com/elastic/security-team/issues/4167#issuecomment …
> Remedy problems in automated tests.

- tests/commonlib/io_utils.py
- tests/commonlib/utils.py
- tests/product/tests/test_file_system_rules.py
- tests/product/tests/test_k8s_objects_rules.py
- tests/product/tests/test_process_api_server_rules.py
- tests/product/tests/test_process_controller_manager_rules.py
- tests/product/tests/test_process_etcd_rules.py
- tests/product/tests/test_process_kubelet_rules.py
- tests/product/tests/test_process_scheduler_rules.py
Use of OPA decision logs to match findings against expected findings is now deprecated.
The deprecated function `get_evaluation` has been renamed to `get_logs_evaluation` but not yet deleted, because it's still useful for debugging.
Resolves: https://github.com/elastic/security-team/issues/4049
> Use Elasticsearch events for automated testing.

- .github/workflows/cloudbeat-ci.yml
- Remove tmate actions
- Extend test run time to 55 mins to accommodate API tests
- add concurrency to limit executions to one per pr
> Fix-pre-merge-ci

- tests/commonlib/docker_wrapper.py
- tests/commonlib/kubernetes.py
- tests/deploy/mock-pod.yml
- tests/product/tests/data/k8s_object/k8s_object_rules.py
- tests/product/tests/test_k8s_objects_rules.py
- tests/product/tests/test_process_controller_manager_rules.py
- tests/product/tests/test_process_etcd_rules.py
Most of the problems occur in resource-matching logic that tries to find the right ES event to compare the expected evaluation against, which is harder to do for K8S resources than other resource types.
Inserting a per-testcase UUID into the K8S object's metadata that is being tested allows for much simpler resource-matching than the recursion logic in the [`dict_contains`](https://github.com/elastic/cloudbeat/blob/298e0d2e1cb0c7414f16bf5ea287f1bb5bc4850b/tests/commonlib/utils.py#L87) utility.
Resolves: https://github.com/elastic/security-team/issues/4312
> Fix broken k8s_object_rules tests.

- _meta/config/cloudbeat.common.yml.tmpl
- beater/validator_test.go
- cloudbeat.reference.yml
- cloudbeat.yml
- config/config.go
- config/config_test.go
- evaluator/bundle_test.go
- resources/fetchersManager/factory_test.go
This PR updates the expected integration's input types and rename `dataYaml` to `runtimeCfg`.
Related:
- https://github.com/elastic/integrations/pull/3968
> Update CSP integration input types

- resources/fetchers/kube_factory.go
- resources/fetchers/kube_fetcher.go
- resources/fetchers/kube_fetcher_test.go
The launcher interface is responsible for receiving config updates from Fleet.
When we get a new config, the launcher is stopping the existing cloudbeat and creates a new one with the new config.
The kube-fetcher is being re-created as part of this process, yet, the k8s watchers are not initiated because the sync object is global.
This PR solves this issue by creating a new sync object every time we re-create the kube-fetcher.
> Bug fix - init kube watchers upon reconfiguration

- README.md
- beater/cloudbeat.go
- scripts/remote_edit_config.sh
Resolves https://github.com/elastic/cloudbeat/issues/242
This PR changes the way the `remote_edit_config.sh` works.
In order to find the configuration file path:
Instead of assuming the architecture and the version being run remote, we iteratively find the next folder name by its expected prefix.
> Remote config editing fixes

- evaluator/evaluator.go
- evaluator/opa.go
- evaluator/opa_test.go
- resources/fetchersManager/data.go
- resources/fetching/fetcher.go
- tests/commonlib/utils.py
- transformer/events_creator.go
- transformer/events_creator_test.go
Related to https://github.com/elastic/security-team/issues/3782
> feat: ecs event spec

- JUSTFILE
Separate `create-kind-cluster` to `elastic-stack-connect-kind`.
This fix the dependency `cleanup-create-local-helm-cluster` has on `create-kind-cluster` but it should not be connected to the stack network.
Thanks @yashtewari
> fix: connect kind cluster to elastic-package network

- .github/workflows/Periodic-CI.yml
- .github/workflows/cloudbeat-ci.yml
updates extractions/setup-just@v1 action to use `GITHUB_TOKEN` in order to avoid [rate-limiting errors](https://github.com/elastic/cloudbeat/actions/runs/3078654006/jobs/4974428235#step:4:6) like here:
ref:
- https://github.com/extractions/setup-just#usage
> Use GitHub token in setup-just action

- .github/workflows/unit-test.yml
Limits dependency reviews to pr only
https://github.com/elastic/cloudbeat/actions/runs/3050543387/jobs/4917744157
> fix depedency scanner on push event

- .gitignore
- deploy/kustomize/overlays/cloudbeat-vanilla-agent/.fleet-token.env
- deploy/kustomize/overlays/cloudbeat-vanilla-agent/README.md
- deploy/kustomize/overlays/cloudbeat-vanilla-agent/kustomization.yml
- deploy/kustomize/overlays/cloudbeat-vanilla-agent/manifests.yaml
- deploy/kustomize/overlays/cloudbeat-vanilla-agent/patches/patchs.yaml
It is hard to run development flow that requires the Agent deployment that runs custom Cloudbeat binary 
Add manifests and Kustomize files to setup the Agent in Kind cluster.
This is required when the agent is needed to be part of the dev flow 
The instructions are in the [README.md](https://github.com/olegsu/cloudbeat/blob/93f8cb797239c02556e1c690944aaed4a112a26c/deploy/kustomize/overlays/cloudbeat-vanilla-agent/README.md)
> feat: deploy agent on kind cluster

- .golangci.yaml
- launcher/launcher.go
- resources/fetchers/ecr_fetcher.go
- resources/fetchers/process_fetcher.go
- resources/fetchersManager/factory.go
Related to #388 
This PR includes also:
1. Update all the logger calls where the regular `go vet` would report
2. Update the CI script `golangci-lint` configuration to run custom `print.funcs`
Normally `go vet` runs on a lot of functions signatures (the full list `go tool vet help printf`), but not the one that in [logp](https://github.com/elastic/elastic-agent-libs/blob/main/logp/logger.go)
To overcome this `go vet` allow to add additional functions to check.
By setting `-printfuncs="Infof,Debugf,Warnf,Errorf,Fatalf,Panicf,DPanicf"` we can make sure that all the logger calls are covered
* Install [golangci-lint ](https://golangci-lint.run/usage/install/#macos)
* Run `golangci-lint run`
When having formatting issues, for example `l.log.Infof("Waiting for initial reconfiguration from Fleet …
> Unwrap errors

- .github/workflows/cloudbeat-ci.yml
- go.mod
- go.sum
- tests/commonlib/utils.py
- tests/configuration.py
- tests/product/tests/data/process/process_test_cases.py
- tests/product/tests/test_process_api_server_rules.py
- tests/product/tests/test_process_controller_manager_rules.py
- tests/product/tests/test_process_etcd_rules.py
- tests/product/tests/test_process_kubelet_rules.py
- tests/product/tests/test_process_scheduler_rules.py
The timeout bump is a workaround until we figure out why some findings are taking a long time to show up in the ES index after [this change](https://github.com/elastic/cloudbeat/commit/3c17c16c80c4ab6b78efa6bfaed8e9ec90fcecb2).
> Mend CI with resource identifiers, increased timeout.

- resources/fetchersManager/data.go
We've replaced cycle_id with event.sequence variable.
This variable marks the cycle of the fetched resources and should allow us to get a complete picture of system posture.
Previously we've used a unique id and now we've switched to UNIX timestamps.
Notice that in the current code we are triggering multiple goroutines for every fetching cycle (routine per fetcher).
Passing the UNIX timestamp that is being pulled for every fetcher will cause a scenario where we might have fetchers from the same cycle having different sequence numbers (due to golang timing of calling the goroutines and context switches).
I've unified the UNIX timestamp in order to avoid mismatched cycles for fetchers.
This also affects our CI testing infrastructure that queries the event.sequence variable and makes …
> Event sequence mismatch between fetchers of same cycle

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/workflows/coverage.yml
- .github/workflows/packaging.yml
- .github/workflows/unit-test.yml
Removes trigger on pr assignment which causes an extra invocation when mergify processes a pr.
- Fixes:
https://github.com/elastic/cloudbeat/pull/437
**Checklist**
> remove trigger type "assigned" on pr

- justfile
**Motivation**
ELK local stack and cloudbeat (in kind cluster) do not share a network by default.
So the following setup will cause the cloudbeat to throw `DNS error` to stderr
```bash
elastic-package stack up -vd
just deploy-cloudbeat
```
To resolve this it is required to connect the kind container network to ELK by running`just elastic-stack-connect-kind`
> feat: connect kind to elk network

- transformer/events_creator.go
Transformer allocated the `eventMetadata` once and re-used it for all of the events that it sends to ES.
The underlying `elastic-agent-libs/mapstr` implementation is non-concurrent.
This causes a panic of concurrent read/writes in race scenarios when sending events.
Fixes 
- #461
> Map concurrent access panic for events metadata

- _meta/config/cloudbeat.common.yml.tmpl
- beater/cloudbeat.go
- cloudbeat.reference.yml
- cloudbeat.yml
- config/config.go
- config/config_test.go
- deploy/kustomize/overlays/cloudbeat-eks/cloudbeat.yml
- deploy/kustomize/overlays/cloudbeat-vanilla/cloudbeat.yml
- evaluator/opa.go
- evaluator/opa_test.go
- justfile
- leaderelection/leaderelection.go
- resources/fetchersManager/factory.go
- resources/fetchersManager/factory_aws_test.go
- resources/fetchersManager/factory_test.go
- tests/deploy/cloudbeat-eks-pytest.yaml
- tests/deploy/cloudbeat-pytest.yml
- tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
- transformer/common_data_provider.go
- transformer/common_data_provider_test.go
- transformer/transformer.go
As part of elastic-agent V2 changes, the beat no longer receives configuration as an array of streams (where only the first one is populated). Instead, it accepts the config itself right away.
This PR removes the stream abstraction from our code for all different running methods.
**Checklist**
> Remove streams struct

- .github/workflows/unit-test.yml
Removing the `*_mock.go` files from the coverage report
> skip mock files in coverage report

- .github/workflows/Periodic-CI.yml
- .github/workflows/cloudbeat-ci.yml
- .github/workflows/packaging.yml
- .github/workflows/publish-test-results.yml
- .github/workflows/unit-test.yml
- Makefile
- go.mod
- Pin GH workers' ubuntu image to 20.04
- Exclude elastic-agent from our dependencies see https://github.com/elastic/apm-server/pull/9668 for ref
- Fixes: https://github.com/elastic/cloudbeat/issues/546
**Checklist**
> Pin GH workers ubuntu image to 20.04

- .github/workflows/Periodic-CI.yml
- .github/workflows/unit-test.yml
Use the `setup-go` action with the `go-version-file` input so it reads the file `.go-version`
Avoid the logic to read and create env variables and use the undocumented `.go-version-file` 
See https://github.com/actions/setup-go/pull/295
> actions: use go-version-file: .go-version

- scripts/make/generate_notice.py
The encoding change did not cause the issue, but using `with` to fix the linters incorrectly was the root cause. I used ChatGPT in order to confirm it, very impressive:
> Fixing Packaging workflow using chatGPT 

- config/config.go
- launcher/errors.go
- launcher/errors_test.go
- launcher/launcher.go
Moving launcher errors to be defined on the same package as the launcher.
The motivation behind maintaining the two on the same package is that the launcher already has the errors as a dependency. The launcher can report a different status to the fleet based on the returned error. Which means, the errors better be defined on the same package.
**Checklist**
> Move launcher errors under launcher package

- version/settings.go
Fixing commit SHA time format to support mapping it in ES as `date` type
- Related: https://github.com/elastic/integrations/pull/4923
**Screenshots**
**Checklist**
> fix cloudbeat commit SHA field format

- evaluator/debug_logger/plugin.go
- evaluator/opa_test.go
Add more information about the decision log cloudbeat prints.
- decision id
- decision input
- decision result
Resolves https://github.com/elastic/cloudbeat/issues/533
**Checklist**
> Enrich decision log message with OPA fields

- resources/providers/awslib/iam/client_mock.go
- resources/providers/awslib/iam/iam.go
- resources/providers/awslib/iam/policy.go
- resources/providers/awslib/iam/root_account.go
- resources/providers/awslib/iam/user.go
- resources/providers/awslib/iam/user_test.go
- version/policy.go
Adds attached and inline policies information of the IAM user.
Update csp policies version to `v1.2.10`.
- Related: https://github.com/elastic/csp-security-policies/pull/173
**Checklist**
> Add policy data to the IAM user [CSPM]

- beater/cloudbeat.go
- launcher/launcher.go
- launcher/launcher_test.go
- uniqueness/leaderelection.go
The launcher commonly referred to Cloudbeat on logs as "The Beater, " the interface that Cloudbeat implements.
Those lines of logs are confusing and make no sense to an outside reader.
This PR replaces all occurrences with "Cloudbeat".
> Launcher logging adds beater name

- version/version.go
Updates references to the new release 8.6.2.
Merge after the release 8.6.1.
> [Release] Update version to 8.6.2

- dataprovider/k8s_data_provider.go
- resources/providers/cluster_provider.go
- resources/providers/cluster_provider_test.go
When running `cis_aws` benchmark the `ClusterNameProvider` will panic with an error that this benchmark does not support yet.
We assume that in most cases `cis_aws` benchmark will be running on a standalone instance (ec2) and not as part of a cluster. 
This is problematic panic when running this locally as well (@jeniawhite)
The first solution is to just return an empty string as anyway the [transformer](https://github.com/elastic/cloudbeat/blob/main/transformer/events_creator.go#L98) will not add the `orchestrator.cluster.name` field in case of an empty string.
> feat: update cluster name provider when running cis_aws benchmark

- resources/fetchers/monitoring_factory.go
- resources/fetchers/monitoring_factory_test.go
- resources/fetchers/monitoring_fetcher.go
- resources/fetchers/monitoring_fetcher_test.go
- resources/fetchers/network_factory.go
- resources/fetchers/network_factory_test.go
- resources/fetchers/network_fetcher.go
- resources/fetchers/network_fetcher_test.go
- resources/fetchers/rds_factory.go
- resources/fetchers/rds_factory_test.go
- resources/fetchers/rds_fetcher.go
- resources/fetchers/rds_fetcher_test.go
- resources/providers/awslib/ec2/ec2.go
- resources/providers/awslib/ec2/mock_elastic_compute.go
- resources/providers/awslib/ec2/provider.go
- resources/providers/awslib/ec2/provider_test.go
- resources/providers/awslib/multi_region.go
- resources/providers/awslib/multi_region_test.go
- resources/providers/awslib/rds/provider.go
- resources/providers/awslib/rds/provider_test.go
- resources/providers/awslib/rds/rds.go
- resources/providers/awslib/securityhub/mock_service.go
- resources/providers/awslib/securityhub/provider.go
- resources/providers/awslib/securityhub/provider_test.go
- resources/providers/awslib/securityhub/securityhub.go
refactor securityhub, ec2 and rds providers to be multi-regional like the other aws providers we have
> refactor: align providers to be multi regional

- .github/workflows/unit-test.yml
After multiple attemps to run the `unit-test.yml` in the CI, it seems that it the racing validation step causes a timeout.
Instead of increasing the step timeout, and by that increasing the general time that the CI runs, we would like to merge to steps in the CI:
- The race validation check
- Coverage and unit test step
By merging these two into one step we hope to get the same result in less CI time.
> Reduce time in Cloudbeat CI

- flavors/vulnerability.go
- go.mod
- go.sum
- resources/providers/awslib/ec2/provider.go
- resources/providers/awslib/ec2/provider_test.go
- vulnerability/fetcher.go
- vulnerability/replicator.go
- vulnerability/runner.go
- vulnerability/scanner.go
- vulnerability/verifier.go
- vulnerability/worker.go
Adding the ability to configure the AWS config that `Trivy` uses in order to scan EBS snapshots.
Currently, this is a temporary solution and is based on a forked `Trivy` using the following commits:
- https://github.com/masahiro331/go-ebs-file/pull/2
- https://github.com/jeniawhite/trivy/commit/77c59c27eda01973cfb9fe86e16bc3b19b4fa70b
- Related: https://github.com/elastic/cloudbeat/issues/727
> Support Trivy credentials configuration

- beater/beater.go
- config/config.go
Same as the integration works. We expect the `v1.config.type` to contain `cspm | kspm | vuln_mgmt`.
> Rename deployment to type as in integration

- tests/product/tests/data/aws/aws_logging_test_cases.py
- tests/product/tests/test_aws_logging_rules.py
- tests/pyproject.toml
- Implemented functional tests for AWS Logging Rules (3.1-..-3.11)
1. Build cloudbeat and opa bundle
```
go mod vendor
go build -v
```
2. Create k8s cluster
`just create-kind-cluster "kind-mono"`
3.  Deploy ELK environment
`just deploy-tests-helm pre_merge ./tests/deploy/values/ci.yml`
4. Export environment vars:
```
export ES_HOST=http://127.0.0.1:9200
export ES_USERNAME="kibana_system"
export ES_PASSWORD="changeme"
```
_Note_: After deploying ELK stack Kibana is available at: http://127.0.0.1:5601
5. Start cloudbeat
`./cloudbeat -c "deploy/aws/cloudbeat-aws.yml" --path.logs "/tmp" `
6. Wait 5-10 minutes
7. Execute tests
```
cd ./tests
poetry run pytest -k "aws" --alluredir=./allure/results/ --clean-alluredir 
```
8. Open Allure report
`allure serve ./allure/results`
> AWS Logging functional tests

- scripts/make/generate_notice.py
Cloudbeat has a dependency, https://github.com/spdx/tools-golang, with a license file named LICENSE.docs which is not supported by go-license-detector.
In order to support this, I add an override for this repository as suggested https://github.com/elastic/go-licence-detector/pull/21#discussion_r1142966373.
> Add license override for spdx/tools-golang

- .github/workflows/eks-ci.yml
According to the latest runs ([run-1](https://github.com/elastic/cloudbeat/actions/runs/4502240659/jobs/7923779699), [run-2](https://github.com/elastic/cloudbeat/actions/runs/4498747448/jobs/7915746694)) the build job in eks-ci flow is not finished and interrupted due timeout event.
This PR updates Build job timeout-minutes value.
> Update build timeout in eks-ci workflow

- Makefile
This fix is done in order to fix the [publish workflow](https://internal-ci.elastic.co/blue/organizations/jenkins/cloudbeat%2Fcloudbeat-mbp/detail/main/363/pipeline) temporarily
> global mage call in Makefile

- Makefile
Since we have added hermit, we no longer need to use a compiled version of our magefile.
instead, since `mage` command is always available, calling `mage` will use the installed version on the machine.
This change is trying to resolve the `make release` command that has had problems lately and blocks us from publishing cloudbeat artifacts.
> Remove compilation of magefile

- deploy/cloudformation/elastic-agent-ec2.yml
- tests/integration/tests/test_standalone_agent_integration.py
- vulnerability/scanner.go
Modifying the CloudFormation stack for vulnerability management to run on arm64 instead of amd64.
The credentials provider changes are made in order to let the flow work OOTB for elastic-agent that run on EC2 (prod).
As both beats and trivy can read the credentials from the disk.
Resolves https://github.com/elastic/cloudbeat/issues/604
> CloudFormation template runs arm64

- .github/workflows/k8s-ci.yml
- tests/commonlib/elastic_wrapper.py
- tests/integration/tests/conftest.py
Pre-merge agent test suite is failed on retrieving findings (k8s object findings are not exist).
This PR increases agent's startup timeout and updates query of data to be retrieved.
> pre-merge agent tests failure

- config/config.go
- config/config_test.go
- dataprovider/data_provider.go
- dataprovider/mock_common_data_provider.go
- dataprovider/providers/aws/data_provider.go
- dataprovider/providers/aws/data_provider_test.go
- dataprovider/providers/k8s/data_provider.go
- dataprovider/providers/k8s/data_provider_test.go
- flavors/common.go
- flavors/flavors.go
- flavors/posture.go
- flavors/vulnerability.go
- resources/fetching/fetcher.go
- resources/providers/awslib/ec2/provider.go
- transformer/events_creator.go
- transformer/events_creator_test.go
- vulnerability/events_creator.go
- vulnerability/fetcher.go
- vulnerability/scanner.go
- vulnerability/worker.go
I made more extensive changes than required for vulnerability management because we have an additional CSPM task of adding the region to the findings and I don't want code duplications.
1. Add cloud data to the vm events.
2. Modify the events creator to act as another pipeline step.
Added fields
- Related: https://github.com/elastic/cloudbeat/issues/745
> Add cloud data to VM events

- deploy/vulnerability/cloudbeat-vuln-mgmt.yml
With this file part of the repository we could easily run cloudbeat and trigger the vulnerability management flavor.
For example using vscode, adding to `launch.json` the snippet:
```
{
"name": "Launch Vulnerability Management",
"type": "go",
"request": "launch",
"mode": "auto",
"program": "${workspaceFolder}/main.go",
"args": ["-c", "deploy/vulnerability/cloudbeat-vuln-mgmt.yml", "-e", "-d", "'*'"],
"env": {
"ES_HOST": "https://localhost:9200",
"ES_USERNAME": "elastic",
"ES_PASSWORD": "changeme",
}
}
```
- Related: https://github.com/elastic/cloudbeat/issues/833
> Add cloudbeat.yml for vulnerability management

- deploy/cloudformation/elastic-agent-ec2.yml
- vulnerability/events_creator.go
Improve score and version picking by adding a fallback logic in case Trivy vul does not have `nvd` attributes.
<details>
<summary>Finding example</summary>
```json
{
"_index": ".ds-logs-cloud_security_posture.vulnerabilities-default-2023.04.18-000001",
"_id": "3zJLnYcBY-LT9Xmo-d6A",
"_version": 1,
"_score": 0,
"_source": {
"agent": {
"name": "Uris-MacBook-Pro.local",
"id": "048fc243-cb89-4eb8-bc92-34904f4ae5c7",
"type": "cloudbeat",
"ephemeral_id": "88fdd2b2-1496-400b-9947-7883e4008469",
"version": "8.8.0"
},
"resource": {
"name": "cspm-bc4",
"id": "0708b5252a6556c9c"
},
"vulnerability": {
"severity": "MEDIUM",
"package": {
"fixed_version": "1.5.16, 1.6.12",
"name": "github.com/containerd/containerd",
"version": "v1.5.13"
},
"description": "containerd is an open source container runtime. …
```
> Add fallback logic to vulnerability events creation

- vulnerability/events_creator.go
We have a dynamic code that looks at Trivy's reported data_source and takes its CVSS information.
This is done in order to calculate the `score.version` and `score.base` values.
In some cases, Trivy reports a source that is non-existent in the CVSS array and that array doesn't have an NVD source.
This creates weird behavior in the FE.
I've implemented a priority mechanism that attempts to pull the reported source, if non existent it will attempt to pull any other source besides NVD, and if there aren't anything resorts to NVD or empty fields if the CVSS is empty.
> Vulnerability pull available CVSS data sources

- resources/fetchers/iam_factory.go
- resources/fetchers/iam_fetcher.go
- resources/fetchers/iam_fetcher_test.go
- resources/fetching/fetcher.go
- resources/providers/awslib/iam/iam.go
- resources/providers/awslib/iam/mock_access_management.go
- resources/providers/awslib/iam/mock_client.go
- resources/providers/awslib/iam/server_cerfiticates.go
- resources/providers/awslib/iam/server_certificates_test.go
1. Uses `aws iam list-server-certificates` to fetch resources
2. Adds a new sub type: `aws-iam-server-certificate`
- closes https://github.com/elastic/csp-security-policies/issues/221
> Fetch AWS iam server-certificates

- magefile.go
Always cleanup the /tmp directory when `BuildOpaBundle` is run.
This improves behaviour in the case where a build is cancelled mid-build (e.g. with Ctrl-C). Before the change, the directory would remain in /tmp and on the next build cloning it would fail, leading to a confusing error.
> magefile: BuildOpaBundle: Always cleanup

- pipeline/pipeline_test.go
- resources/utils/testhelper/helper.go
CollectResources is problematic because it tests using len() on a channel, which only uses the length of the queue of the channel.
Fixes: https://github.com/elastic/cloudbeat/issues/902
> Fix TestStep race condition

- deploy/cloudformation/elastic-agent-ec2.yml
Update the ec2 compute instance type to be with the newest Graviton processor.
Improve CPU utilization and avoid CPU throttling.
- Fixes: https://github.com/elastic/security-team/issues/6338
> [CNVM] Update cloudformation ec2 instance type

- deploy/cloudformation/elastic-agent-ec2.yml
Sets a default value to the CloudFormation parameter `ElasticArtifactServer`.
The default value is the URL of released artifacts, for dev process it should be replaced with snapshot or build candidates.
- Related: https://github.com/elastic/cloudbeat/issues/937
> Set default value to CloudFormation param ElasticArtifactServer

- resources/providers/awslib/s3/provider.go
- version/policy.go
S3 provider now handles missing public access block configurations properly (logs a debug message instead of an error). Policy version has been updated to one that can handle null public access block configurations properly.
Related: https://github.com/elastic/csp-security-policies/pull/234
Related: https://github.com/elastic/csp-security-policies/issues/233
> S3 provider handles missing public access block config better

- deploy/cloudformation/README.md
- deploy/cloudformation/config.go
- deploy/cloudformation/elastic-agent-ec2.yml
- deploy/cloudformation/gomain.go
Add a CSPM integration option in the CloudFormation template, using a map to change the IAM role permissions depending on which of the two options is used
- Fixes: https://github.com/elastic/cloudbeat/issues/596
> CloudFormation: Add CSPM integration option

- .github/workflows/publish-artifacts.yml
Line that needs to be updated: https://github.com/elastic/integrations/blob/85ee85e17a97be4a222b6071ce9e29207ae30e3b/packages/cloud_security_posture/manifest.yml#L138
- Related: #596
- Related: #975
>  CloudFormation: Upload to path without "vuln-mgmt"

- _meta/config/cloudbeat.common.yml.tmpl
- cloudbeat.reference.yml
- cloudbeat.yml
- deploy/kustomize/overlays/cloudbeat-vanilla-nocert/cloudbeat.yml
- tests/commonlib/io_utils.py
- tests/deploy/cloudbeat-pytest.yml
- tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
- tests/deploy/sa-agent-pytest.yml
- tests/product/tests/conftest.py
- tests/product/tests/data/file_system/file_system_test_cases.py
This seems to be just a configuration error. Both the rego rules and the `Glob` go code seem to work fine.
I've updated all config files and added new functional tests.
[finding.json](https://github.com/elastic/cloudbeat/files/11498836/finding.json.txt)
Made by running `docker exec -it kind-multi-worker bash` and then `cd /etc/kubernetes/pki` and creating non-root-owned files under `somedir/`
> k8s CIS 1.1.19: Scan pki/ folder recursively

- deploy/cloudformation/ec2-types.yml
- In our test EC2 template, I've added the option to encrypt the root volume.
- Some root volumes where misconfigured (mixed between `/dev/sda1` and `/dev/xvda`).
> Test EC2 types CFT allow to encrypt instances

- .github/workflows/k8s-ci.yml
Skipping AWS post-merge tests until resource migration is done @gurevichdmitry 
- Related: https://github.com/elastic/security-team/issues/6757
- Related: https://github.com/elastic/security-team/issues/6760
> Skip AWS post-merge tests

- version/version.go
Elastic machine forced pushed commits update the version branch to 8.10.0, which needs to be reverted.
> Update version.go for the 8.9 branch

- deploy/cloudformation/elastic-agent-ec2.yml
Add a `BlockDeviceMappings` section to increase the root device volume size.
In AMI we are using the root device is `/dev/sda1`.
- Fixes: https://github.com/elastic/cloudbeat/issues/1098
> [CloudFormation] Increase scanner volume size

- .github/workflows/test-environment.yml
- deploy/test-environments/fleet_api/src/agents_enrolled.py
- deploy/test-environments/fleet_api/src/api/agent_policy_api.py
- deploy/test-environments/fleet_api/src/api/package_policy_api.py
- deploy/test-environments/fleet_api/src/configuration_fleet.py
- deploy/test-environments/fleet_api/src/install_cnvm_integration.py
- deploy/test-environments/fleet_api/src/install_cspm_integration.py
- deploy/test-environments/fleet_api/src/install_kspm_eks_integration.py
- deploy/test-environments/fleet_api/src/install_kspm_unmanaged_integration.py
- deploy/test-environments/fleet_api/src/purge_integrations.py
- deploy/test-environments/fleet_api/src/state_file_manager.py
- deploy/test-environments/fleet_api/src/utils.py
Add step in the sanity environment to wait for all agents to be enrolled to the fleet
- https://github.com/elastic/cloudbeat/issues/700
> [Sanity] Assert that all agents are enrolled

- vulnerability/fetcher_test.go
- vulnerability/replicator_test.go
- vulnerability/verifier_test.go
Convert tests into test suites to fix a bug where the `goleak.VerifyNone()` doesn't work.
> Convert to test suites

- dev-docs/sanity-workflow.md
I create a PR to specify which environment to create the API keys.  After I created workflows with  ec-stack API Keys from Elastic Cloud Staging. I received the error below.
I specify the correct Elastic Cloud environment with  a link
> Update ec-API-Key bullet in sanity workflow doc

- .github/workflows/test-environment.yml
- README.md
- deploy/test-environments/delete_env.sh
- deploy/test-environments/variables.tf
- dev-docs/Cloud-Env-Testing.md
- justfile
- tests/README.md
Updated the Cloud testing env workflow usage readme for:
- Clarity Improvements
- Recent changes docs updates
- Added information for the manual deletion script
- Cloud env name will be shown in github actions UI
- Improved cloud stack deletion script:
- can run from any folder
- wrapped by just command
- interactive flow is togglable 
tested with `just delete-cloud-env "oren" "amir"`
and docs:
> Improving Cloud Deployment test env docs

- deploy/cloudformation/README.md
- deploy/cloudformation/config.go
The `just deploy-cloudformation` command uses a config file to get the deployment configuration.
The config file has recently changed from `.env` to `config.env` (or `config.json`, `config.yml`) and we want to keep it that way as the sanity job is dependent on that.
> Fix CloudFormation deployment config file

- resources/fetching/fetchers/gcp/assets_fetcher.go
- resources/fetching/fetchers/gcp/assets_fetcher_test.go
updates the `GcpAssetTypes` map to be less repetitive and derive the sub types from the first/last segments of the asset types
examples:
- `cloudkms.googleapis.com/CryptoKey` -> `gcp-cloudkms-crypto-key`
- `iam.googleapis.com/ServiceAccount` -> `gcp-iam-service-account`
> Derive GCP sub types from asset type

- .golangci.yaml
- .pre-commit-config.yaml
- flavors/benchmark/gcp.go
- resources/fetching/fetchers/gcp/assets_fetcher.go
- resources/providers/gcplib/inventory/provider.go
- resources/providers/gcplib/inventory/provider_test.go
- vulnerability/events_creator_test.go
Replaces goimports with gci: https://github.com/daixiang0/gci
> golangci-lint: Make order of imports deterministic

- resources/fetching/factory/aws_factory_test.go
- resources/utils/testhelper/helper.go
- resources/utils/testhelper/helper_test.go
`TestNewCisAwsOrganizationFactory_Leak` has failed in many CI pipelines
> Make CollectResourcesWithTimeout less flaky

- config/config.go
- config/config_test.go
- flavors/benchmark/benchmark_test.go
As discussed with @JordanSh, for consistency with the url in the integration: https://github.com/elastic/cloudbeat/blob/25057a13ee224e9a220a53693ab1cdc1cf6ecf5f/.github/workflows/publish-cloudformation.yml#L37
- https://github.com/elastic/cloudbeat/issues/1036
- https://github.com/elastic/kibana/pull/162571
> [AWS Orgs] Replace underscore in configuration with hyphen

- dataprovider/providers/cloud/data_provider.go
- dataprovider/providers/cloud/data_provider_test.go
- dataprovider/providers/cloud/option.go
- flavors/benchmark/gcp_test.go
- resources/providers/gcplib/identity/identity_provider.go
- resources/providers/gcplib/identity/identity_provider_test.go
Assign GCP fields to `cloud.account.id` and `cloud.account.name` to align with AWS CSPM. 
We communicate with the ECS team to modify and extend the cloud schema in the future
- Related: https://github.com/elastic/cloudbeat/issues/1120
> Update GCP's ECS fields

- .github/workflows/cnvm-ci.yml
- .github/workflows/destroy-environment.yml
- .github/workflows/eks-ci.yml
- .github/workflows/publish-cloudformation.yml
- .github/workflows/publish-test-results.yml
- .github/workflows/test-environment.yml
switching to `pull_request_target` trigger instead of `pull_request` since PRs with `pull_request` from public forks [don't have the right permission](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).
> Switching trigger for the CNVM workflow

- flavors/client.go
- flavors/posture.go
`publisher` component buffers events and send them altogether to elasticsearch.
Same as the vulnerability flavor, posture can use the same component and keep our code DRY.
https://github.com/elastic/cloudbeat/pull/1142
> Posture use publisher component

- .github/workflows/publish-cloudformation.yml
- scripts/publish_cft.sh
Because of a limitation in the `cloud_security_posutre` integration, all CloudFormation templates should have an identical signature (version + date).
- Fixes: https://github.com/elastic/cloudbeat/issues/1132
> CloudFormation templates have identical signature

- vulnerability/events_creator.go
- vulnerability/worker_test.go
Following this request:
- https://github.com/elastic/cloudbeat/issues/983#issuecomment-1640000632
- Related: https://github.com/elastic/cloudbeat/issues/983
> [CNVM] Index updates

- deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
Validate that the `OrganizationalUnitIds` parameter is as expected
From the AWS docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
> A regular expression that represents the patterns to allow for String
> or CommaDelimitedList types. When applied on a parameter of type
> String, the pattern must match the entire parameter value provided.
> When applied to a parameter of type CommaDelimitedList, the pattern
> must match each value in the list.
So, we are allowed to use it in a CommaDelimitedList
Sources for regex patterns:
- https://docs.aws.amazon.com/organizations/latest/APIReference/API_OrganizationalUnit.html
- https://docs.aws.amazon.com/organizations/latest/APIReference/API_Root.html
- Related: …
> [AWS Orgs] CloudFormation: Validate OrganizationalUnitIds

- resources/fetching/fetchers/gcp/assets_fetcher.go
Use asset's data fields when available.
The main improvement is to use the display name when it is available.
before the change: `102234624624808999868`
After the change: `csp-ci-github`
- Fixes: https://github.com/elastic/cloudbeat/issues/1324
> [CIS GCP] Make resource name more friendly

- .pre-commit-config.yaml
Automatically fix `golangci-lint` failures before commit, e.g. `gci`.
https://github.com/elastic/cloudbeat/pull/1335#pullrequestreview-1619727906
> pre-commit: golangci-lint: Auto fix supported failures

- .github/workflows/cloudbeat-ci.yml
- .github/workflows/eks-ci.yml
- .github/workflows/k8s-ci.yml
looks like `Build` already includes a call to `BuildOpaBundle`:
https://github.com/elastic/cloudbeat/blob/48e17af899402c9121ce177379294053e396f482/magefile.go#L81-L84
> Remove extra build step

- .gitignore
- vulnerability/events_creator.go
- vulnerability/events_creator_test.go
This PR moves the logic existing in Kibana to Cloudbeat of populating the NVD link instead of the Aquasec link in `vulnerability.reference` field.
the field should look like the following after the change
```
{
...
"reference": "https://nvd.nist.gov/vuln/detail/CVE-2022-3080",
...
}
```
- Fixes: https://github.com/elastic/cloudbeat/issues/869#top
> Populate vulnerability.reference with a link to NVD

- .github/workflows/destroy-environment.yml
- .github/workflows/test-environment.yml
- .github/workflows/weekly-enviroment.yml
- dev-docs/CSPM-Cloud-Deployment.md
- dev-docs/Cloud-Env-Testing.md
- dev-docs/Development.md
- dev-docs/ELK-Deployment.md
Updating our [cloud env testing](https://github.com/elastic/cloudbeat/blob/main/dev-docs/Cloud-Env-Testing.md) to use our cloud organization API key by default.
> Update Cloud Env workflow to default to our Org API key

- dataprovider/providers/common/data_provider.go
- dataprovider/providers/common/data_provider_test.go
- flavors/posture.go
The data held by the CDP is static and should not be decoded for every new cloudbeat event.
Instead of decoding the shared data every new event, the common data provider will do so upon initialization.
- #1305
> Make common data provider more efficient

- version/version.go
Updates references to the new release 8.10.3.
Merge after the release 8.10.2.
> [Release] Update version to 8.10.3

- .github/workflows/gcp-ci.yml
skip gcp integration test as it's flaky 
see https://github.com/elastic/cloudbeat/issues/1371
> [GCP] skip gcp ci

- resources/fetching/fetcher.go
- resources/fetching/fetchers/azure/assets_fetcher.go
- resources/fetching/fetchers/azure/assets_fetcher_test.go
- resources/providers/azurelib/inventory/asset.go
adds a new asset type to be fetched for evaluation, goes with https://github.com/elastic/csp-security-policies/pull/316
> [Azure] Add websites asset type

- .github/dependabot.yml
Groups should update together, helps avoid PR spam and make sure we always keep dependencies in sync for each cloud provider.
Closes https://github.com/elastic/cloudbeat/pull/1429
Closes https://github.com/elastic/cloudbeat/pull/1430
Closes https://github.com/elastic/cloudbeat/pull/1431
Closes https://github.com/elastic/cloudbeat/pull/1433
> Dependabot: Create groups

- resources/providers/azurelib/inventory/provider.go
- resources/providers/azurelib/inventory/provider_test.go
Following the QA cycle we've noticed that an SKU rule is not being evaluated.
This is because we did not map the SKU property and OPA wasn't evaluating the rule.
- Related: https://github.com/elastic/cloudbeat/issues/1256
> Azure add mapping for SKU property

- resources/fetching/fetchers/azure/assets_fetcher.go
- resources/fetching/fetchers/azure/assets_fetcher_test.go
We need to evaluate activity rules as a batch and not as singles
- Related: https://github.com/elastic/cloudbeat/issues/1256
- ### Checklist
> Azure remove activity logs from single fetcher

- deploy/cloudformation/elastic-agent-ec2-cnvm.yml
- deploy/cloudformation/elastic-agent-ec2-cspm.yml
This reverts commit d4ad5d46cd8ac89d6bee232cbc70f07b595f0aff before the 8.11 release.
- Related: https://github.com/elastic/cloudbeat/pull/1415
> Revert "CloudFormation: Fix missing tags in cloud-security account"

- .ci/scripts/update-beats.sh
Easier to debug and follow what commands are running in the CI.
> update-beats: Set -x flag to print commands

- .ci/scripts/update-beats.sh
- .github/workflows/update-beats.yml
Use hermit for proper go version.
For some reason, running `git diff` triggers the PR correctly. I haven't determined exactly why.
Example PR: https://github.com/orestisfl/cloudbeat/pull/14. Note that this is done without the apm CI actions because I don't have vault access. Instead, I called updatecli directly from the GH action: https://github.com/orestisfl/cloudbeat/blob/d517e53a6d27679912f6a89fd55660317b98df68/.github/workflows/update-beats.yml
CC @v1v
> update-beats: Use hermit for go

- .ci/updatecli/scripts/update-hermit.sh
- .ci/updatecli/updatecli.d/update-hermit.yml
Added to hermit pipeline to reduce PR spam and because some of the hooks
are inter-connected with hermit packages. For example, this way we are
going to have the same version of `regal` in hermit and pre-commit.
> Updatecli: Update pre-commit as well

- .ci/updatecli/scripts/update-hermit.sh
`hermit upgrade` will only upgrade minor versions for packages that use semantic versioning. Not all of our hermit packages use semantic versioning and even for those that do, we want to be at least aware of new major versions and update to those if they don't cause too much of a breakage.
Uninstalling and re-installing will always install to the latest major version.
This fixes an issue with `pre-commit autoupdate` not being able to update our `black` hook because it's too old to understand newer syntax.
Additionally, skip the poetry-based checks in pre-commit as that is not installed.
Example PR: https://github.com/orestisfl/cloudbeat/pull/23
> update-hermit: Consider major versions as well

- config/config.go
- resources/providers/azurelib/auth/credentials.go
- resources/providers/azurelib/auth/credentials_test.go
Based on the discussion in [this comment](https://github.com/elastic/integrations/pull/8376#discussion_r1390451815), this PR adds the Azure credentials type in the config and uses it to identify which Azure `TokenCredential` to use.
Enumerator values are on par with [this PR](https://github.com/elastic/kibana/pull/171069).
> Add Azure credentials type in configuration 

- config/config.go
- resources/providers/azurelib/auth/credentials.go
- resources/providers/azurelib/auth/credentials_test.go
Add the missing `arm_template` azure credential type, which is the value is used on ARM Template deployments.
Fixes: https://github.com/elastic/cloudbeat/issues/1563
> Azure credentials config: Add missing type `arm_template`

- deploy/test-environments/delete_env.sh
Fixing a case when IGNORE_PREFIX equals to an empty string and we remove groups with grep -v
> IGNORE_PREFIX fix in delete_env

- config/config.go
- resources/providers/azurelib/auth/credentials.go
- resources/providers/azurelib/auth/credentials_test.go
Add Azure credential type value `manual` for backward compatibility reasons to cover upgrade while Manual setup access was selected. 
- Related: https://github.com/elastic/cloudbeat/issues/1563
> Add azure credential type: manual (backwards compatibility value)

- .ci/updatecli/updatecli.d/update-beats.yml
- .ci/updatecli/updatecli.d/update-golang.yml
- .ci/updatecli/updatecli.d/update-hermit.yml
- .ci/updatecli/values.yml
- .github/workflows/updatecli.yml
Extended the [updatecli](https://github.com/elastic/cloudbeat/actions/workflows/updatecli.yml) workflow to check and update Go and Beat versions on latest active branches too.
The identification of what is the latest active branch was made fetching all remote branches, filtering what matches `MAJOR.MINOR` pattern, [sort by version](https://man7.org/linux/man-pages/man1/sort.1.html) (`sort -V`) and selecting the highest version.
- Fixes https://github.com/elastic/cloudbeat/issues/1550
> Update updatecli workflow to also apply changes to latest active branch

- deploy/test-environments/delete_env.sh
Removed `role-assignment-deployment` from the deployment lists because it is not being deployed on resource group level.
This is deployed at the subscription level.
There are no resources that it creates and it just maps the role.
As part of the deletion of `cloudbeat-vm` this mapping should get purged as well.
> Remove role deployment from deletion of env

- .github/workflows/updatecli.yml
Fix backport of go releases to latest branch.
For some reason the command `git branch -r` was not fetching the remote branches properly inside the workflow. The command `git ls-remote --heads` does (tested from this PR, see the commit history). The rest of the changes were adapting to the format returned by `git ls-remote`
- Fixes https://github.com/elastic/cloudbeat/issues/1550
> Fix updatecli run for last supported branches

- .ci/updatecli/scripts/hermit-bump-go.sh
- .ci/updatecli/scripts/update-beats.sh
In order to run properly update go and beats we need to have the update scripts on 8.11 branch too (future releases will already have it since those scripts are on main)
- Fixes https://github.com/elastic/cloudbeat/issues/1550
> Backport updatecli scripts

- .github/workflows/test-environment.yml
- deploy/azure/ARM-for-single-account.json
- deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py
This uses the "default" deployment template which includes a better UI for selecting resource group to deploy to. This also removes one sub-deployment for the resource group as the user can select/create one from the UI.
Previously, it was thought that we need the subscription deployment template schema to deploy role assignments to the subscription level.
Removes the location parameter and use the native Azure selector.
Additionally, fixes an issue with the deployment not working across different regions (#1619). Fix is just to include the location in the name for the role assignment deployment. This one is the only sub-deployment that needs to be fixed because the rest deploy at the resource group level. The subscription level sub-deployment requires the `location` property, otherwise …
> Azure ARM: Use resource group deployment schema

- .github/workflows/k8s-ci.yml
The k8s CI tests are flaky and run as pre-merge, which is a requirement for every PR. Since the feature is in the support stage, we avoid making any changes to that codebase in our PRs. This PR skips pre-merge k8s tests.
> Skipping pre-merge k8s tests

- version/version.go
Updates references to the new release 8.11.3.
Merge after the release 8.11.2.
> [Release] Update version to 8.11.3

- resources/fetching/fetchers/azure/assets_enricher.go
- resources/fetching/fetchers/azure/assets_enricher_storage_account.go
- resources/fetching/fetchers/azure/assets_enricher_storage_account_test.go
- resources/fetching/fetchers/azure/assets_enricher_test.go
- resources/fetching/fetchers/azure/assets_fetcher.go
- resources/fetching/fetchers/azure/assets_fetcher_test.go
This PR introduces Azure asset "enricher" interface and creates a slice of enrichers in Azure asset fetcher.
After the assets are fetched from the provider, azure assset fetcher runs all enrichers serially and enriches the assets.
> Azure Assets Enricher

- .pre-commit-config.yaml
- evaluator/opa_test.go
- flavors/benchmark/aws_org_test.go
- flavors/benchmark/aws_test.go
- flavors/benchmark/builder/benchmark_test.go
- flavors/benchmark/builder/builder_test.go
- flavors/benchmark/builder/k8s_test.go
- flavors/benchmark/eks_test.go
- flavors/benchmark/k8s_test.go
- flavors/publisher_test.go
- flavors/repeater_test.go
- launcher/launcher_test.go
- resources/fetching/cycle/cache_test.go
- resources/fetching/fetchers/k8s/kube_fetcher_test.go
- resources/fetching/manager/manager_test.go
- resources/fetching/preset/aws_org_preset_test.go
- resources/providers/awslib/cached_region_selector_test.go
- resources/providers/azurelib/governance/management_group_test.go
- resources/utils/testhelper/helper.go
- resources/utils/testhelper/helper_test.go
- uniqueness/leaderelection_test.go
- vulnerability/events_creator_test.go
- vulnerability/fetcher_test.go
- vulnerability/replicator_test.go
- vulnerability/runner_test.go
- vulnerability/verifier_test.go
- vulnerability/worker_test.go
Adds a pre-commit action for running the tests. By using the timeout flag, we ensure that all new tests that are long will be properly skipped when the short flag is used.
Fixes #1140
> Skip long tests when -short flag is set

- .ci/updatecli/scripts/update-mods.sh
- .ci/updatecli/updatecli.d/update-mods.yml
- .github/workflows/updatecli.yml
Since dependabot is often encountering issues updating our go.mod, we can work-around this by updating everything with updatecli.
Since not all modules can be upgraded without failures, the script updates modules one-by-one and reverts the changes if build & test fails.
> updatecli: Update go mod dependencies

- .github/workflows/updatecli.yml
Run the jobs earlier so that they ready to merge on Monday morning.
> updatecli: Run cron job earlier

- .ci/updatecli/scripts/update-mods.sh
On the last run, the job timed-out after 6 hours because of the amount of work it had to do. We can do the updates in 5-hour batches in these cases.
For the $SECONDS variable see https://stackoverflow.com/a/31663949
> update-mods.sh: Break after 5 hours

- launcher/launcher_test.go
Since 10ms can be too little time and beater might exit gracefully in that time span.
Fixes #1703
> TestLauncherStopTimeout: Increase post-grace sleep duration

- .golangci.yaml
I've skipped `bytes.Buffer.WriteString` since it always returns a `nil` error.
Description: This rule warns when errors returned by a function are not explicitly handled on the caller side.
Configuration: function names regexp patterns to ignore
Related: #1669
> revive: Enable unhandled-error

- .golangci.yaml
- dataprovider/enrich.go
- dataprovider/providers/k8s/id_provider.go
- dataprovider/providers/k8s/id_provider_test.go
- flavors/benchmark/aws_org_test.go
- flavors/benchmark/k8s_helper.go
- resources/fetching/fetchers/k8s/file_system_fetcher_test.go
These are also flagged by Goland so it's nice to have
unexported-naming
Description: this rule warns on wrongly named un-exported symbols, i.e. un-exported symbols whose name start with a capital letter.
Configuration: N/A
unexported-return
Description: This rule warns when an exported function or method returns a value of an un-exported type.
Configuration: N/A
Related: #1669
> revive: Enable unexported-naming and unexported-return

- .golangci.yaml
- resources/providers/awslib/iam/access_analyzer_test.go
- resources/providers/azurelib/inventory/provider_test.go
Description: To improve the readability of code, it is recommended to reduce the indentation as much as possible. This rule highlights redundant else-blocks that can be eliminated from the code.
More information:
https://go.dev/wiki/CodeReviewComments#indent-error-flow
Related: #1669
> revive: Enable indent-error-flow rule

- flavors/publisher_test.go
*this is an alternative solution to https://github.com/elastic/cloudbeat/pull/1678*
TestPublisher_HandleEvents tests the events batching functionality of `flavors.Publisher`. This is a tricky test because it spawns multiple goroutines and want to verify that x events were published in Y period. With litlle external interference the tests work great. But if for any reason multiple go routines run 1ms or 2ms later, or 1 go routine delays 10ms, the test will fail. 
For example, in a 45ms period, it's expected:
```
1 event at 10ms
2 event at 20ms
3 event at 30ms
4 event at 40ms
------- Publish 10 events
5 event at 50ms
6 event at 60ms
7 event at 70ms
8 event at 80ms
------- Publish 26 events
9 event at 90ms
------- Publish 9 events
```
But what happens sometimes is:
```
1 event at 11ms
2 …
```
> Add wait step to avoid too tight publishing period

- .golangci.yaml
- resources/providers/azurelib/inventory/provider.go
- resources/providers/gcplib/auth/credentials.go
Description: In Go it is idiomatic to minimize nesting statements, a typical example is to avoid if-then-else constructions. This rule spots constructions like
```go
if cond {
// do something
} else {
// do other thing
return ...
}
```
where the `if` condition may be inverted in order to reduce nesting:
```go
if !cond {
// do other thing
return ...
}
// do something
```
Related: #1669
> revive: Enable early-return

- .golangci.yaml
- flavors/benchmark/aws.go
- flavors/benchmark/aws_org.go
- flavors/benchmark/azure.go
- flavors/benchmark/eks.go
- flavors/benchmark/gcp.go
- flavors/benchmark/k8s.go
- resources/providers/gcplib/inventory/provider.go
- vulnerability/fetcher_test.go
confusing-results
Description: Function or methods that return multiple, no named, values of the same type could induce error.
function-result-limit
Description: Functions returning too many results can be hard to understand/use.
Configuration: (int) the maximum allowed return values
Related: #1669
> revive: Enable confusing-results and function-result-limit

- go.mod
- go.sum
Updating github.com/lestrrat-go/jwx package to the latest version 1.2.27
Also backporting to 8.11
> feat: update jwx pkg

- .github/workflows/azure-ci.yml
In order to test and run Azure CI, I would need to trigger it manually because it doesn't run the CI via pull requests and pulls the new workflow file
> Adding workflow dispatch to Azure CI due to Azure CI retrigger bugs

- resources/providers/awslib/cloudtrail/provider.go
Use Cloud Trail ARN when get trail status and event selectors instead of Cloud Trail name
- Fixes: https://github.com/elastic/cloudbeat/issues/1750
> Use Cloud Trail ARN when get trail status and event selectors

- .github/workflows/rerun-flaky-workflows.yml
This PR adds permissions to the "Rerun Flaky Workflows" workflow to allow the rerun action
> Add permissions for rerun action

- .github/workflows/k8s-ci.yml
- .github/workflows/test-environment.yml
This PR fixes the scenario when workflow fails in any of the steps, and cleanup resources checkbox is selected, the workflow won't delete the environment.
Evidence of the workflow run with cleanup resources selected and executed during a failure can be found [here](https://github.com/elastic/cloudbeat/actions/runs/7438955180/job/20238277675).
> [Create Environment] Update cleanup step statement

- resources/fetching/fetchers/azure/assets_enricher_sql_server.go
- resources/fetching/fetchers/azure/assets_enricher_sql_server_test.go
- resources/fetching/fetchers/azure/assets_fetcher_test.go
- resources/providers/azurelib/inventory/asset.go
- resources/providers/azurelib/inventory/mock_provider_api.go
- resources/providers/azurelib/inventory/provider.go
- resources/providers/azurelib/inventory/sql_server.go
- resources/providers/azurelib/inventory/sql_server_test.go
- resources/providers/azurelib/mock_provider_api.go
- resources/providers/azurelib/provider.go
- security-policies/RULES.md
- security-policies/bundle/compliance/cis_azure/rules/cis_4_1_5/data.yaml
- security-policies/bundle/compliance/cis_azure/rules/cis_4_1_5/rule.rego
- security-policies/bundle/compliance/cis_azure/rules/cis_4_1_5/test.rego
Implement CIS 4.1.5.
Goal: verify that all sql server databases, with a name different of master, have Transparent Data Encryption enabled.
The change was verified locally.
With TDE enabled
Without
Some code refactoring on the tests was also made.
There is a resource `microsoft.sql/servers/databases` in the ARG. However, this resource doesn't contain the sql server instance name, which we need to make the call to retrieve TDE. I could not find an attribute to correlate servers with databases.
The decision made was to evaluate this rule as part of the SQLServer resource, and on enrichment level fetch all the databases, and for each database, call the TDE.
- Related https://github.com/elastic/cloudbeat/issues/1417
> CIS Azure 4.1.5

- security-policies/README.md
- security-policies/RULES.md
- security-policies/bundle/compliance/cis_azure/rules/cis_4_3_1/rule.rego
- security-policies/bundle/compliance/cis_azure/rules/cis_4_3_1/test.rego
- security-policies/bundle/compliance/cis_azure/rules/cis_4_3_8/data.yaml
- security-policies/bundle/compliance/cis_azure/rules/cis_4_3_8/rule.rego
- security-policies/bundle/compliance/cis_azure/rules/cis_4_3_8/test.rego
- security-policies/bundle/compliance/cis_azure/test_data.rego
Implement CIS Azure 4.3.8 Ensure 'Infrastructure double encryption' for PostgreSQL Database Server is 'Enabled'
I could not test this rule passing because it's available only for postgre single servers, and that's not [possible to be created anymore](https://learn.microsoft.com/en-us/azure/postgresql/single-server/whats-happening-to-postgresql-single-server). In 2025 it will be completely phased out.
But is possible to see it failing on the already created servers with Disabled infrastructure double encryption
- Related https://github.com/elastic/cloudbeat/issues/1417
> CIS Azure 4.3.8

- resources/fetching/fetchers/azure/assets_enricher_postgresql.go
- resources/fetching/fetchers/azure/assets_enricher_postgresql_test.go
- resources/fetching/fetchers/azure/assets_fetcher_test.go
- resources/providers/azurelib/inventory/asset.go
- resources/providers/azurelib/inventory/mock_postgresql_provider_api.go
- resources/providers/azurelib/inventory/postgresql_provider.go
- resources/providers/azurelib/inventory/postgresql_provider_test.go
- resources/providers/azurelib/mock_provider_api.go
- security-policies/README.md
- security-policies/RULES.md
- security-policies/bundle/compliance/cis_azure/rules/cis_4_3_7/data.yaml
- security-policies/bundle/compliance/cis_azure/rules/cis_4_3_7/rule.rego
- security-policies/bundle/compliance/cis_azure/rules/cis_4_3_7/test.rego
Implement CIS Azure 4.3.7 Ensure 'Allow access to Azure services' for PostgreSQL Database Server is disabled
✅  When the allow access to azure service is _not enabled_ it **passes**
✅  When the allow access to azure service is _enabled_ it **fails**
On the flexible UI you enabled through: 
✅  When the allow access to azure service is _not enabled_ it **passes**
✅  When the allow access to azure service is _enabled_ it **fails**
On the single UI you enable through
- Related https://github.com/elastic/cloudbeat/issues/1417
> CIS Azure 4.3.7

- .github/workflows/destroy-environment.yml
- .github/workflows/test-environment.yml
- .github/workflows/test-gcp-dm.yml
- .github/workflows/upgrade-environment.yml
- .github/workflows/weekly-enviroment.yml
- deploy/cloud/main.tf
- deploy/cloud/modules/ec/variables.tf
- deploy/cloud/variables.tf
- deploy/test-environments/README.md
- deploy/test-environments/delete_env.sh
- deploy/test-environments/main.tf
- deploy/test-environments/variables.tf
- deploy/weekly-environment/main.tf
- dev-docs/Cloud-Env-Testing.md
This PR adds the option to select the Select the Environment URL to the Create Environment Github action workflow, that allows to create instances on the Production or on the QA environment
> [Cloud Security] Select the Environment Url for Create Environment

- tests/README.md
- tests/commonlib/elastic_wrapper.py
- tests/configuration.py
- tests/conftest.py
Connecting to a local ES instance brought up with elastic-package was failing due to SSL verification. This PR adds a flag to skip the verification when needed.
> Add flag to skip SSL verification and docs on how to run agains local ES

- resources/fetching/fetchers/k8s/process_fetcher.go
- resources/fetching/fetchers/k8s/process_fetcher_test.go
- resources/fetching/preset/k8s_preset.go
**The issue**
KSPM produces false negative results when [calico](https://www.tigera.io/project-calico/) CNI is used in the cluster.  
The failing rules examine specific running processes in Kubernetes nodes.
**Note: how cloudbeat fetches processes information about running processes:**
Cloudbeat fetches all running process IDs, and for each one of those, it retrieves the name from [proc status file](https://man7.org/linux/man-pages/man5/proc.5.html) (_check section `/proc/pid/status`_). 
Based on the **name** retrieved from the status file, Cloudbeat filters the processes that evaluates.  The names cloudbeat filters are included in the code, for example, for self-managed k8s clusters are in the file `resources/fetching/preset/k8s_preset.go` in `vanillaRequiredProcesses` map. 
**Root …
> k8s fix process name matching

- .github/workflows/test-environment.yml
The "Create Environment" workflow output the following warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/login@v1, aws-actions/configure-aws-credentials@v2, hashicorp/vault-action@v2.7.4, slackapi/slack-github-action@v1.24.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
As for now, `hashicorp/vault-action@v2.7.4` and `slackapi/slack-github-action@v1.24.0` are the latest versions and can't be updated.
Upgrading the rest of the dependencies that use the deprecated node.js version.
> Update dependencies of Create Environment action

- .github/workflows/k8s-ci.yml
This PR enables post merge k8s testing ci.
> Enable post-merge k8s ci

- .github/dependabot.yml
- .github/workflows/eks-ci.yml
- .github/workflows/k8s-ci.yml
- .github/workflows/periodic-ci.yml
The latest version of the upload-artifact action has revealed [this issue](https://github.com/actions/upload-artifact/issues/478), causing a break in the k8s CI. As mentioned in [this comment](https://github.com/actions/upload-artifact/issues/279#issuecomment-1859601387), this issue does not occur with actions/upload-artifact@v3. This PR reverts the upload-artifact action version from v4 to v3.
> Revert upload artifact version from v4 to v3

- .github/dependabot.yml
- .github/workflows/eks-ci.yml
- .github/workflows/periodic-ci.yml
- .github/workflows/unit-test.yml
This PR reverts download-artifact action from v4 to v3.
> Revert download artifacts from v4 to v3

- .github/dependabot.yml
This PR fixes pattern to ignore upgrade of upload-artifact and download-artifact to v4
> Update dependabot pattern to ignore github actions update

- tests/product/tests/data/azure/azure_networking_test_cases.py
Add integration tests for CIS Azure 6.1, 6.2, 6.3, 6.4
Based on:
- [test-vm-pass](https://portal.azure.com/#@elastic365.onmicrosoft.com/resource/subscriptions/ef111ee2-6c89-4b09-92c6-5c2321f888df/resourceGroups/AZURECLOUDBEATCITESTS/providers/Microsoft.Compute/virtualMachines/TEST-VM-PASS/overview)
- [test-vm-fail](https://portal.azure.com/#@elastic365.onmicrosoft.com/resource/subscriptions/ef111ee2-6c89-4b09-92c6-5c2321f888df/resourceGroups/AzureCloudbeatCITests/providers/Microsoft.Compute/virtualMachines/test-vm-fail/overview)
On the test-vm-pass no inbound port is open. On the test-vm-fail, [ports that fail the 4 rules are configured](https://portal.azure.com/#@elastic365.onmicrosoft.com/resource/subscriptions/ef111ee2-6c89-4b09-92c6-5c2321f888df/resourceGroups/AzureCloudbeatCITests/pro …
> Add IT for CIS Azure 6.1, 6.2, 6.3, 6.4

- .github/workflows/bump-version.yml
- scripts/bump_cloudbeat.sh
- scripts/bump_integration.sh
this PR adds a dispatch workflow that should be triggered manually whenever we release a new version. it takes a single input:
- next cloudbeat version (major.minor) 
then it bumps all the required files in both repos
for a test-run, i bumped `8.14.0` to `8.15.0` (current is actually `8.13.0` but this was just for demo purpose)
- [intergrations PR](https://github.com/elastic/integrations/pull/8958)
- [cloudbeat versions PR](https://github.com/elastic/cloudbeat/pull/1851)
- [cloudbeat hermit PR](https://github.com/elastic/cloudbeat/pull/1852)
looks like this:
- closes https://github.com/elastic/cloudbeat/issues/1675
> add workflow for version bumps

- version/version.go
Updates references to the new release 8.12.2.
Merge after the release 8.12.1.
> [Release] Update version to 8.12.2

- internal/resources/fetching/fetchers/azure/assets_enricher_keyvault.go
- internal/resources/fetching/fetchers/azure/assets_enricher_keyvault_test.go
- internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
- internal/resources/providers/azurelib/inventory/asset.go
- internal/resources/providers/azurelib/inventory/keyvault_provider.go
- internal/resources/providers/azurelib/inventory/keyvault_provider_test.go
- internal/resources/providers/azurelib/inventory/mock_key_vault_provider_api.go
- internal/resources/providers/azurelib/mock_provider_api.go
- internal/resources/providers/azurelib/provider.go
- security-policies/README.md
- security-policies/RULES.md
- security-policies/bundle/compliance/cis_azure/rules/cis_5_1_5/data.yaml
- security-policies/bundle/compliance/cis_azure/rules/cis_5_1_5/rule.rego
- security-policies/bundle/compliance/cis_azure/rules/cis_5_1_5/test.rego
- tests/product/tests/data/azure/azure_key_vault_test_cases.py
adds CIS Azure 5.1.5: 
> Ensure that logging for Azure Key Vault is 'Enabled'
specifically - 
> Ensure that `storageAccountId` is set as appropriate. 
this is assumed to be some id and not `null`
> Ensure that `AuditEvent` is checked
this is assumed to be that `category` is `AuditEvent` or `categoryGroup` is `audit`/`allLogs` 
> ... and the retention days is set to 180 days or as appropriate
this is up for discussion with product, currently not implemented as it can't be audited as the original CIS intention given this feature is now deprecated. 
- closes https://github.com/elastic/cloudbeat/issues/1757
> CIS Azure 5.1.5

- .github/workflows/bump-version.yml
this fixes an issue where the workflow calls the `bump_integration.sh` script while the current HEAD is on previous release, which ended up running a previous version of the script.
> checkout main for running integration bump script

- internal/resources/providers/aws_cis/monitoring/filter_pattern_parser.go
- security-policies/bundle/compliance/cis_aws/rules/cis_4_15/rule.rego
- security-policies/bundle/compliance/cis_aws/rules/cis_4_15/test.rego
- security-policies/bundle/compliance/cis_aws/rules/cis_4_4/rule.rego
- security-policies/bundle/compliance/cis_aws/rules/cis_4_4/test.rego
- security-policies/bundle/compliance/policy/aws_cloudtrail/pattern.rego
Problems addressed with this PR
- Due to the strategy on  `MetricFilterPattern` embedding `simpleExpression` and `complexExpression` there was a conflicting field `Operator` which was not being marshalled to json.
- Rules 4.4 and 4.15 were failing due to bad manual parsing.
- Fixes https://github.com/elastic/cloudbeat/issues/1506
> Fix confliciting fields and bugs on the rules

- internal/resources/fetching/fetchers/k8s/process_fetcher.go
Improve the error logs the process fetcher generates
- Related: https://github.com/elastic/cloudbeat/issues/2008
> Process fetcher improve error logs

- deploy/azure/ARM-for-single-account.dev.json
- deploy/azure/ARM-for-single-account.json
Add `Microsoft.Web/sites/config/Read` and `Microsoft.Web/sites/config/list/Action` permissions. The permissions needed were indicated by the error message in `cloudbeat` logs:
```
ESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
"error": {
"code": "AuthorizationFailed",
"message": "The client '[REDACTED]' with object id '[REDACTED]' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/[REDACTED]/resourceGroups/azurecloudbeatcitests/providers/Microsoft.Web/sites/test-app-service-pass/config/authsettings' or the scope is invalid. If access was recently granted, please refresh your credentials."
}
} …
```
> Add permissions for Azure CIS 9.1 rule

- internal/flavors/benchmark/aws_org.go
initializes `cloud.NewDataProvider` with `awsIdentity` account so the `cloud.provider.name` is included 
| before 	| after 	|   	
|-------------------	|------------------------------	|
|![Screenshot 2024-03-18 at 16 01 19](https://github.com/elastic/cloudbeat/assets/20814186/4ca549a6-3695-42cf-bd8a-37ca79968dc8)              	|                              ![Screenshot 2024-03-18 at 16 00 58](https://github.com/elastic/cloudbeat/assets/20814186/b2ba7c51-9aa2-4480-9351-063ca20650a4)	|   
- fixes https://github.com/elastic/kibana/issues/178772
> add aws provider name to org scan

- .github/workflows/ci.yml
> Make ci pull_request_target

- .github/workflows/ci.yml
Fix the missing comment in PRs with allure report.
> fix ci results comment

- deploy/test-environments/delete_env.sh
- deploy/test-environments/main.tf
This PR adds a new tag `deployment` for the create environment Terraform script.
Additionally, it fixes the delete environment script to handle the case where no GCP deployment exists. Instead of failing, the script now provides a message stating that no GCP deployments need to be deleted.
> [Create Environment] Add new tag and fix delete env script

- scripts/bump_cloudbeat.sh
- scripts/bump_integration.sh
- cleaned up code, renamed some variables for consistency, moved some lines
- added label creation for mergify
- added workflow summary with links to PRs
-----
PR for release docs (https://github.com/elastic/security-team/pull/8552)
> minor improvements to version bump workflow

- version/version.go
Updates references to the new release 8.13.2.
Merge after the release 8.13.1.
> [Release] Update version to 8.13.2

- .github/workflows/ci.yml
bump timeout so we can maybe see logs in failed runs 
cc @oren-zohar going to need a force merge here as CNVM-CI is going to fail
> update CNVM timeout

- .github/workflows/rerun-flaky-workflows.yml
This PR enhances the rerun workflow to send a Slack notification when the event differs from a pull request
> Update rerun workflow to send Slack notification if event name is not a pull request.

- internal/flavors/benchmark/gcp.go
- internal/resources/fetching/fetcher.go
- internal/resources/fetching/fetchers/gcp/assets_fetcher.go
- internal/resources/fetching/fetchers/gcp/log_sink_fetcher.go
- internal/resources/fetching/fetchers/gcp/monitoring_fetcher.go
- internal/resources/fetching/fetchers/gcp/policies_fetcher.go
- internal/resources/fetching/fetchers/gcp/service_usage_fetcher.go
- internal/resources/providers/gcplib/inventory/provider.go
- internal/resources/providers/gcplib/inventory/provider_test.go
AWS and Azure both use `fetching.CloudAccountMetadata` to describe cloud metadata and `resource.GetMetadata` to populate it (via `EnrichEvent` of cloud data provider). 
GCP uses `EcsGcp` to describe the same cloud metadata and uses `resource.GetElasticCommonData` to populate it. 
this PR makes it so that GCP describes and populates cloud data the same way AWS and Azure do it. 
- closes https://github.com/elastic/cloudbeat/issues/2079
> use CloudAccountMetadata in GCP

- security-policies/RULES.md
- tests/product/tests/data/azure/azure_database_service_test_cases.py
`Azure Database for MySQL - Single Server` is being retired by Azure portal. It is no longer possible to create them via UI or via CLI. Existing resources need migration to `Flexible Server` type. Our test resources have already been migrated.
```
~ az mysql server list --resource-group AzureCloudbeatCITests
[]
~ az mysql flexible-server list --resource-group AzureCloudbeatCITests | jq '.[] | .name'
"rule-441"
"rule-441-fail"
"test-mysql-db-fail"
"test-mysql-db-pass"
```
See https://learn.microsoft.com/en-us/azure/mysql/single-server/whats-happening-to-mysql-single-server
Slack thread by @moukoublen: https://elastic.slack.com/archives/C056S4ZJW3W/p1712239647533959
No
> Disable integration tests for Azure 4.4.1

- tests/integration/tests/test_sanity_checks.py
Re-enable some AWS (`cloud-compute`, `cloud-storage`) and EKS (`file`) sanity checks. Increased initial timeout.
<details><summary>Successful run of the Tests workflow</summary>
</details>
<details><summary>New AWS sanity checks passed</summary>
</details>
<details><summary>Successful run of the EKS-CI workflow</summary>
</details>
<details><summary>New EKS sanity checks passed - config 1</summary>
</details>
<details><summary>New EKS sanity checks passed - config 2</summary>
</details>
<details><summary>Successful sanity tests in Create Environment workflow</summary>
URL: <a href="https://github.com/elastic/cloudbeat/actions/runs/8538309690/job/23390701836">https://github.com/elastic/cloudbeat/actions/runs/8538309690/job/23390701836</a>
</details>
Fixes …
> Re-enable some AWS and EKS sanity checks in integration tests

- deploy/deployment-manager/deploy.sh
Currently, the deployment created using IAC lacks any label making it hard to identify the owner.
This PR adds an owner label according to the user who is logged in to Cloud Shell.
> [CIS GCP] Add owner label to a deployment manager deployments

- .github/workflows/rerun-flaky-workflows.yml
This PR updates rerun workflow with env vars
> Update rerun workflow

- internal/flavors/asset_inventory.go
- internal/flavors/benchmark/strategy.go
- internal/flavors/benchmark/strategy_test.go
- internal/flavors/posture.go
Initialize logger in all `awslib.IdentityProvider` usages to avoid panic when trying to log error.
Fixes: https://github.com/elastic/cloudbeat/issues/2096
> fix panic due to missing logger of aws IdentityProvider

- .github/actions/slack-notification/README.md
- .github/actions/slack-notification/action.yml
This PR updates the Slack channel name from `csp-qa-alerts` to `cloud-sec-qa-alerts`
> Update slack channel name

- .github/actions/aws-ci/action.yml
- .github/workflows/cloudformation-ci.yml
- deploy/aws/cloudbeat-aws.yml
- deploy/cloudformation/elastic-agent-direct-access-key-cspm-organization.yml
- deploy/cloudformation/elastic-agent-direct-access-key-cspm.yml
- scripts/publish_cft.sh
Fixes: https://github.com/elastic/cloudbeat/issues/2062
Moved from: https://github.com/elastic/cloudbeat/pull/2066
> Cloudformation access key

- internal/resources/fetching/fetchers/aws/iam_fetcher.go
- internal/resources/fetching/fetchers/aws/iam_fetcher_test.go
- internal/resources/fetching/fetchers/azure/assets_fetcher.go
- internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
- internal/resources/fetching/fetchers/gcp/assets_fetcher.go
- internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go
`user.*` section of our findings and their ECS has been empty so far. This PR adds user details where applicable.
- 1.4 - 1.7 -  enriched; root account
- 1.8, 1.9 - no change; Password Policy not tied to a single user
- 1.10 - 1.15 - enriched; regular users
- 1.16, 1.17 - Policies; enriched; making an assumption based on the [spreadhsheet](https://docs.google.com/spreadsheets/d/1p7m6c-sPn_Orgfc-jwJod9wupvF-2Qp7SDrDLle15_8/edit#gid=124010285), changing `user.effective.*`
- 1.19 - no change; AWS IAM server certificate rule
- 1.20 - no change; AWS Access Analyzer
- 1.23 - enriched
- 1.4, 1.7 - enriched; `idendity-management`
- 1.5, 1.6, 1.8, 1.11 - no change; one finding has a full report on all users and roles (type: `project-management`)
- 1.9, 1.10, 1.12, 1.14, 1.15 - no change; …
> Add correct user info for select IAM resources

- .github/workflows/arm-template-lint.yml
- deploy/azure/ARM-for-organization-account.dev.json
- deploy/azure/ARM-for-organization-account.json
- deploy/azure/ARM-for-single-account.dev.json
- deploy/azure/ARM-for-single-account.json
Add ARM TTK Linter to the github workflow and fix linter errors
Test results available on https://github.com/elastic/cloudbeat/issues/1663#issuecomment-2072021094
- Closes https://github.com/elastic/cloudbeat/issues/1663
> Add Lint ARM Templates step

- go.mod
- internal/flavors/benchmark/gcp.go
- internal/resources/providers/gcplib/inventory/grpc_rate_limiter.go
- internal/resources/providers/gcplib/inventory/grpc_rate_limiter_test.go
- internal/resources/providers/gcplib/inventory/map_cache.go
- internal/resources/providers/gcplib/inventory/map_cache_test.go
- internal/resources/providers/gcplib/inventory/provider.go
- internal/resources/providers/gcplib/inventory/provider_test.go
1. adds rate limiting to the asset inventory client. our current usage is only for `ListAssets`
2. retries requests made by `ListAssets` client whenever they failed due to rate limiting
3. adds a cache to the policies fetcher (using a new cache utility, as we already have 3 caches in this file)
for `ListAssets`, we only use the per-project [quota](https://cloud.google.com/asset-inventory/docs/quota), which is `100 per minute per consumer project`. we do this because:
1. the consumer project (the one consuming the quota) is set by the user when they run `gcloud config set project <project_id>` before deploying the agent. (verified with `gcloud config get billing/quota_project`). 
2. in both our use cases: `single-account` and `organization-account`, we always use a single quota project. we …
> add rate limit to asset inventory

- version/version.go
Updates references to the new release 8.13.5.
Merge after the release 8.13.4.
> [Release] Update version to 8.13.5

- .github/workflows/test-gcp-dm.yml
- deploy/deployment-manager/common.sh
- deploy/deployment-manager/compute_engine.py
- deploy/deployment-manager/compute_engine.py.schema
- deploy/deployment-manager/deploy.sh
- deploy/deployment-manager/deploy_service_account.sh
- deploy/deployment-manager/service_account.py
- deploy/deployment-manager/service_account.py.schema
- deploy/test-environments/delete_gcp_env.sh
- tests/fleet_api/utils.py
- tests/integrations_setup/configuration_fleet.py
- tests/integrations_setup/install_cspm_gcp_integration.py
- this is how a successful deployment looks from a user POV after they ran the service account deployment script in a GCP shell:
- tested we get findings using the generated key by providing it as a JSON blob credentials option on the manual deployment option:
- closes https://github.com/elastic/cloudbeat/issues/2005
> add GCP credentials deployment 

- internal/vulnerability/runner.go
- internal/vulnerability/worker.go
**Clean trivy cache after each cycle** 
Trivy [artifact.NewRunner](https://github.com/aquasecurity/trivy/blob/main/pkg/commands/artifact/run.go#L116) calls [initCache](https://github.com/aquasecurity/trivy/blob/main/pkg/commands/artifact/run.go#L341). 
Depending on the provided configuration, the latter (initCache) could either return a runner or the error `SkipScan` (and nil runner).
In case one of the below flags is `true`, the `artifact.NewRunner` will perform the relevant clean/reset operation and return `SkipScan`. 
* `CacheOptions.ClearCache`
* `DBOptions.Reset`
* `MisconfOptions.ResetPolicyBundle`
This means that:
1. The clean/reset operations are embedded inside `initCache`, called inside `artifact.NewRunner`. We cannot execute them standalonely. 
2. When at least one on those …
> Clean trivy cache before each cycle

- .ci/updatecli/updatecli.d/update-beats.yml
- .ci/updatecli/updatecli.d/update-golang.yml
- .ci/updatecli/updatecli.d/update-hermit.yml
- .ci/updatecli/updatecli.d/update-mods.yml
in https://github.com/elastic/cloudbeat/pull/2224 we've changed to use `cloudsecmachine` token for `update-cli` PRs
seems like although we use its token, the email is not configured and thus [fails](https://github.com/elastic/cloudbeat/pull/2247#issuecomment-2144436482) CLA check 
[commit with no CLA issue](https://github.com/elastic/cloudbeat/commit/ac62cad88db661fd24b6db6d42cb5e165ece1954.patch) 
[commit with CLA issue](https://github.com/elastic/cloudbeat/commit/8c39f78c82735ed0c0b1c057d68341902b67555b.patch)
note the email is set on the first one (`cloudsecmachine@users.noreply.github.com`) but not on the second one (`<>`)
i've changed the email used to be `cloudsecmachine@elastic.co`, should work the same, if not we'll use the other one ^
> add cloudsecmachine email for CI

- magefile.go
> Disable CGO in cloudbeat binary

- internal/inventory/inventory.go
- internal/inventory/inventory_test.go
Asset inventory needs to comply with the datastream index template created by the integration and write permissions granted (it needs to end with `-default`).
- Related https://github.com/elastic/security-team/issues/9066
> [Asset Inventory] Update index to match Index Template

- deploy/cloudformation/elastic-agent-direct-access-key-cspm-organization.yml
- deploy/cloudformation/elastic-agent-direct-access-key-cspm.yml
The Export feature within the Output section allows you to create a named export that other CloudFormation stacks can import. It is not actually needed, and it seems to cause some `internal failure` when we deploy multiple stacks with output exports.
> Remove Export from cf direct keys

- .github/workflows/ci.yml
- .github/workflows/eks-ci.yml
Reverts elastic/cloudbeat#2285 because of broken parallel support (https://github.com/andrcuns/allure-publish-action/issues/40)
> Revert "Bump andrcuns/allure-publish-action from 2.6.0 to 2.7.0 in /.github/workflows"

- .github/workflows/test-environment.yml
- .github/workflows/test-gcp-dm.yml
- deploy/azure/install_agent_az_cli.sh
- deploy/deployment-manager/deploy.sh
This PR introduces tagging for resources deployed in Azure Cloud and GCP. Any resource deployed by the `create environment` workflow will be tagged/labeled with predefined tags. For the GCP DM integration tests workflow, any Elastic Agent deployed will be labeled with `ci:integration` and `owner:${{ github.actor }}` labels.
**GCP elastic agent deployment**
**GCP DM integration tests workflow**
**Azure elastic agent VM**
> Label cloud resources

- internal/inventory/asset.go
- internal/inventory/awsfetcher/fetcher_ec2_instance.go
- internal/inventory/awsfetcher/fetcher_ec2_instance_test.go
- internal/inventory/awsfetcher/fetcher_elb.go
- internal/inventory/awsfetcher/fetcher_elb_test.go
- internal/inventory/awsfetcher/fetcher_iam_policy.go
- internal/inventory/awsfetcher/fetcher_iam_policy_test.go
- internal/inventory/awsfetcher/fetcher_iam_role.go
- internal/inventory/awsfetcher/fetcher_iam_role_test.go
- internal/inventory/awsfetcher/fetcher_iam_user.go
- internal/inventory/awsfetcher/fetcher_iam_user_test.go
- internal/inventory/awsfetcher/fetcher_lambda.go
- internal/inventory/awsfetcher/fetcher_lambda_test.go
- internal/inventory/awsfetcher/fetcher_networking.go
- internal/inventory/awsfetcher/fetcher_rds.go
- internal/inventory/awsfetcher/fetcher_rds_test.go
- internal/inventory/awsfetcher/fetcher_s3_bucket.go
- internal/inventory/awsfetcher/fetcher_s3_bucket_test.go
- internal/inventory/awsfetcher/fetcher_sns.go
- internal/inventory/awsfetcher/fetcher_sns_test.go
- internal/inventory/inventory.go
- internal/inventory/inventory_test.go
- internal/resources/providers/awslib/iam/iam.go
- internal/resources/providers/awslib/iam/user.go
To comply with https://github.com/elastic/security-team/issues/9798 and be able to correlate multiple datasources, Asset Inventory has changed the `asset` field to `entity` field name, converted `id` to a list and removed the `uuid` earlier introduced
-  Related https://github.com/elastic/security-team/issues/9798
- Fixes https://github.com/elastic/security-team/issues/9799
- Fixes https://github.com/elastic/security-team/issues/9823
> Implement new identifier format for asset inventory

- .github/workflows/arm-template-lint.yml
- deploy/azure/ARM-for-single-account.dev.json
- deploy/azure/ARM-for-single-account.json
By setting `resourceGroup` to role assignment, the role assignment has a specific (reduced) scope for the specified resource group.
Role assignment with `resourceGroup` (scope to this specific resource group):
```json
{
"properties": {
"roleDefinitionId": "/subscriptions/<sub id>/providers/Microsoft.Authorization/roleDefinitions/<definition id>",
"principalId": "<pid>",
"principalType": "ServicePrincipal",
"scope": "/subscriptions/<sub id>/resourcegroups/evgb-815bclong"
},
"id": "/subscriptions/<sub id>/resourcegroups/evgb-815bclong/providers/Microsoft.Authorization/roleAssignments/<id>",
"type": "Microsoft.Authorization/roleAssignments",
"name": "<id>"
}
```
Role assignment without `resourceGroup` (scope to the subscription):
```json
{
"properties": {
"roleDefinitionId": …
```
> Fix Azure ARM Template: missing resources

- go.mod
- go.sum
Update `go-git` to latest (`v5.12.0`) in order to address [https://github.com/advisories/GHSA-45x7-px36-x8w8](https://github.com/advisories/GHSA-45x7-px36-x8w8)
- Fixes: https://github.com/elastic/security/issues/2288
> Update go-git version to latest

- .github/workflows/eks-ci.yml
- tests/test_environments/aws/eks_config/test-eks-config-1-node-2-10-kubelet-args.conf
- tests/test_environments/k8s-cloudbeat-tests/values.yaml
After investigating, it was found that the EKS node had been restarted and reverted to its default configuration. After updating the node configuration with custom kubelet settings, the problem was resolved. This PR enables the execution of tests on the EKS config 1 cluster and updates the configuration files used for the EKS cluster.
[Successful Run](https://github.com/elastic/cloudbeat/actions/runs/10198769627)
> eks ci - enable config 1

- .github/actions/docker-images/action.yml
- .github/workflows/ci.yml
- tests/test_environments/k8s-cloudbeat-tests/values.yaml
This PR pins the upload artifacts version to v4.3.4 due to [this bug](https://github.com/actions/upload-artifact/issues/589) and also fixes the k8s CI.
> Update upload artifacts action

- tests/integration/tests/test_cloudbeat_integration.py
This PR skips the leader election integration test, which will be investigated in [this task](https://github.com/elastic/cloudbeat/issues/2383).
> Skip integration test

- internal/inventory/asset.go
- internal/inventory/inventory.go
- internal/inventory/inventory_test.go
- Rollback the previous changes of having asset renamed to entity, because there is no final decision of how should the field be named.
- Add `related.entities` field directly on `inventory.go`. I considered having another structure called `Related` that would the field `entities`. I didn't do it because I don't believe we should duplicate this data, `Asset.Id` is the source of truth, having a duplicated slice could lead to inconsistency, and even if we have a reference, seems like overcomplicating. I considered this `related.entities` as an ECS related concern. The `asset.go` map the domain used inside cloudbeat, and `inventory.go` is dealing with elasticsearch integration, ecs concern and so on. Of course we map the Asset to match ECS, we shouldn't have data translation layers here. But …
> Add `related.entities` to asset inventory

- internal/inventory/inventory.go
- internal/inventory/inventory_test.go
Based on product decision we are moving away from `related.entities` and towards `related.entity`
- Related https://github.com/elastic/security-team/issues/10080
- Related https://github.com/elastic/cloudbeat/pull/2379
- Counterpart of https://github.com/elastic/integrations/pull/10719
> Rename from `related.entities` to `related.entity`

- .github/workflows/ci.yml
Before this change all the PRs were executing these long running jobs, on avg ~15min each run. But the branch with the changes was not the one being tested, rather just main, therefore wasting time and resource. With the ticket https://github.com/elastic/security-team/issues/9129 we will solve this issue. But in the meanwhile, we are disabling these jobs.
> Temporarily disable long running tests

- deploy/test-environments/output.tf
This PR fixes the output values. Since the CloudTrail EC2 machine is optional, the output parameters should not be displayed if it is not deployed.
> fix terraform output values

- .github/actions/hermit/action.yml
Disable GA cache restore and add `free-disk` step for each CI job.
Fixes: https://github.com/elastic/cloudbeat/issues/2446
> GA: disable cache restore

- .github/workflows/test-environment.yml
Move `az login` to fix the following error:
[example](https://github.com/elastic/cloudbeat/actions/runs/10595494543/job/29361391806)
```
Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer: tenant ID was not specified and the default tenant ID could not be determined: obtaining tenant ID: obtaining account details: running Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
```
Also moved `gcp` login before terraform.
> Move az and gcp login to above tf on create env

- internal/flavors/posture.go
- internal/flavors/vulnerability.go
https://github.com/elastic/cloudbeat/blob/main/internal/flavors/posture.go#L111 is panic once a config update is received.
Tested by adding the following snippet to simulate a real update:
`internal/launcher/launcher.go:134`
```go
go func() {
l.log.Info("Starting force reload")
time.Sleep(2 * time.Minute)
l.log.Info("Force reloading")
l.reloader.(*Listener).Reload([]*reload.ConfigWithMeta{{Config: config.NewConfig()}})
}()
```
By debugging I noticed the client was `nil`, and once I assigned it, posture would stop as expected (and config be updated).
- Closes https://github.com/elastic/cloudbeat/issues/2217
> Add missing client to posture flavor

- internal/inventory/ASSETS.md
- internal/inventory/asset.go
- internal/inventory/gcpfetcher/fetcher_assets.go
- internal/resources/providers/gcplib/inventory/asset.go
adds the rest of assets types `gcplib` can fetch using GCP assets inventory api
- needs to be merged first https://github.com/elastic/cloudbeat/pull/2460
- closes https://github.com/elastic/security-team/issues/10431
> Add more GCP assets inventory classifications

- .github/actions/gcp-asset-inventory-ci/action.yml
- .github/actions/wait-for-es-data/action.yml
the failing test case seems to be a matter of timing. 
checking for data after 20 seconds - [fails](https://github.com/elastic/cloudbeat/actions/runs/10870390768/job/30162939379?pr=2528#step:4:438)
checking for data after 40 seconds - [succeeds](https://github.com/elastic/cloudbeat/actions/runs/10870322998/job/30162805992)
not sure why this started happening consistently just now, could be [gcp updates](https://github.com/elastic/cloudbeat/pull/2486/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R92) but i'm not sure i see something definitive in the [changelog](https://github.com/googleapis/google-cloud-go/releases?q=auth&expanded=true)
instead of just bumping the sleep period, i've added a new action - `wait-for-es-data` which is essentially the same thing …
> Fix GCP asset inventory CI

- internal/resources/providers/awslib/iam/password_policy.go
- internal/resources/providers/awslib/iam/password_policy_test.go
There is a bug on aws (based on After reading https://github.com/aws/aws-cli/issues/7265 and https://github.com/aws/aws-cli/issues/8402 reading), which in case of a user deleting the password policy, an `NoSuchEntityException ` will be thrown - while that isn't true because password policies have default values in place.
The impact of such a bug to us is that we receive the API error, log the error and doesn't evaluate the policy on OPA layer, missing this finding on such case.
This PR handles the error, and in case of `NoSuchEntityException`, creates an empty password policy, which will then fail on the OPA layer.
it's important to notice, tho that an empty password policy doesn't represent reality, because there is a password policy in place, it just isn't returned
Manual Test of the …
> Handle password policy not found error

- tests/pylintrc
After updating pylint, we started to get `too-many-positional-arguments` error. E.g https://github.com/elastic/cloudbeat/actions/runs/10991206099/job/30513107030?pr=2550
It was added on latest release https://github.com/pylint-dev/pylint/releases/tag/v3.3.0.
Based we already had the `too-many-arguments` I ignored the `too-many-positional-arguments` too
> Fix `too-many-positional-arguments` error

- .github/workflows/test-gcp-dm.yml
- deploy/deployment-manager/deploy_service_account.sh
there were 2 issues preventing GCP CSPM on agentless from successfully deploying a service account for organizations. the first was a slightly off copy-paste command in [kibana](https://github.com/elastic/kibana/pull/192959) which ended up not passing `ORG_ID` to the deployment script, so the deployment assumed it's for a project. the second issue, after providing `ORG_ID`, the deployment script complained about it being a number and not a string (as per its schema). this is what this PR fixes.
after fixing both of these, i've deployed GCP CSPM on agentless and got findings for an organization account:
- fixes https://github.com/elastic/cloudbeat/issues/2502
> Fix GCP deployment manager formatting

- .github/workflows/weekly-serverless.yml
- deploy/azure/install_agent_az_cli.sh
The Azure installation script previously handled only the minor versions of 8.x branches. With the transition to 9.x, major version handling is now required. This PR adds support for both major and minor version handling.
> Update version compatibility handling

- internal/flavors/benchmark/azure.go
- internal/flavors/benchmark/azure_test.go
Increase Azure fetcher timeout to 70% of cycle period duration.
Related: https://github.com/elastic/cloudbeat/issues/2624
> Increase azure fetcher timeout

- .github/workflows/test-environment.yml
This PR updates the test environment workflow to automatically format labels in compliance with GCP’s requirements. It converts any uppercase letters to lowercase and ensures that no disallowed characters are present.
> Fix GCP Labeling in test environment workflow

- internal/inventory/gcpfetcher/fetcher_assets.go
- tests/product/tests/data/gcp_asset_inventory/test_cases.py
adds test cases for: `project`, `cloud-run service`, `iam role`, `bucket` and `firewall`
remaining test cases: 
- `org`: we don't have a suitable org account for CI tests yet
- `gke cluster`: going to figure out costs before enabling this
- `cloud function`: API not enabled for our account, need to discuss this. 
- closes https://github.com/elastic/cloudbeat/issues/2560
---
<details><summary>for future reference - script to quickly run gcp integration tests locally</summary>
```bash
#!/bin/bash
echo 'Start ES'
docker run -d \
--name es2 \
-e "discovery.type=single-node" \
-e "xpack.security.enabled=false" \
-e "xpack.security.http.ssl.enabled=false" \
-p 9200:9200 \
docker.elastic.co/elasticsearch/elasticsearch:8.15.0
sleep 10
export ES_HOST=http://localhost:9200
export …
```
> azure: add integration tests cases

- internal/vulnerability/runner.go
Avoid Trivy DB image pull quota errors by switching container registries from GHCR to ECR. It is still an official image, just from a mirror.
- Fixes: https://github.com/elastic/cloudbeat/issues/2653
- Related: https://github.com/aquasecurity/trivy/discussions/7538
> [CI] Avoid Trivy DB image pull quota issues

- .github/dependabot.yml
Somehow 8.x already had backport-skip there and when backporting, it got duplicated.
> Remove duplicated backport skip label

- internal/resources/providers/awslib/iam/user.go
Avoid log & return (leads to double log), add more error information on `err` returns.
> iam/user.go: Improve logging

- internal/resources/providers/awslib/sns/provider.go
- internal/resources/providers/awslib/sns/provider_test.go
Agentless agents were having panics on fetching SNS topics.
- Fixes: https://github.com/elastic/cloudbeat/issues/2640
> Fix SNS topics fetch panics on errors

- .github/workflows/weekly-serverless.yml
- tests/integrations_setup/configuration_fleet.py
- tests/integrations_setup/install_agentless_integrations.py
This PR updates the stack version used for installing integrations in the serverless environment and fixes the installation of agentless integration for GCP, which was missing the `project ID`. Additionally, support for saving the state of agentless agents has been added to ensure proper enrollment verification.
[Successful workflow run](https://github.com/elastic/cloudbeat/actions/runs/12250792293)
>  Update serverless workflow to use correct stack version

- tests/Dockerfile
- tests/pyproject.toml
The `poetry export` [command is no longer a default command from poetry ](https://python-poetry.org/docs/cli/#export) (poetry >=2.0).
Therefore this PR install the plugin before running it, and also reference it in the test `pyproject.toml`
> Install poetry export

- .mergify.yml
Fix 8.17 backport label by moving from `backport-8.17` to  `backport-v8.17.0`
> Fix 8.17 backport label

- .buildkite/pipeline.yml
- .buildkite/scripts/package.sh
- .buildkite/scripts/publish.sh
- magefile.go
- version/settings.go
- version/version.go
Add Support for VERSION_QUALIFIER argument during DRA production. 
Add a temporary condition to staging artifacts so can be triggered even from main branch when VERSION_QUALIFIER is passed. (required to upload the first `alpha1` pre release). 
Test for artifacts generation done locally, but the buildkite pipeline will be tested after merge. 
Screenshots after running what buildkite pipeline runs plus VERSION_QUALIFIER env var.
```bash
export VERSION_QUALIFIER='alpha1'
export WORKFLOW='staging'
bash ./.buildkite/scripts/package.sh 
```
Fixes: https://github.com/elastic/security-team/issues/11536
> Add support for VERSION_QUALIFIER DRA

- .github/workflows/ci.yml
- .github/workflows/cloudformation-ci.yml
- .github/workflows/destroy-environment.yml
- .github/workflows/eks-ci.yml
- .github/workflows/packaging.yml
- .github/workflows/publish-cloudformation.yml
- .github/workflows/test-environment.yml
- .github/workflows/unit-test.yml
- .github/workflows/upgrade-environment.yml
See [github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/)
Let's use `ubuntu-22`.
> github-actions: ubuntu-20.04 will be fully retired by April 1, 2025

- .buildkite/pipeline.yml
- .buildkite/scripts/package.sh
- .buildkite/scripts/publish.sh
- .buildkite/scripts/qualifier.sh
In buildkite pipeline scripts (package and publish) get VERSION_QUALIFIER from google bucket (if not already set) for the current branch.
> [buildkite]: get version qualifier from google bucket

- internal/dataprovider/providers/k8s/cluster_name_provider_test.go
One of the k8s suite tests was flaky. In case a valid `kubeconfig` is present on the machine that runs the test, the suite will fail, getting the data from default `kubeconfig` path. As a solution, I set the `KubeConfig` path to something non-existent to ensure we get the expected result and true `kubeconfig` does not interfere.
_The test failing before the fix; Please note an actual cluster name from my `kubeconfig`: `production`._
None, found randomly on my machine.
> [Go] Fix a flaky Kubernetes test setup

- internal/inventory/asset.go
- internal/inventory/gcpfetcher/fetcher_assets.go
- internal/inventory/gcpfetcher/fetcher_assets_test.go
- internal/inventory/inventory.go
- internal/inventory/inventory_test.go
- adds specific asset type enrichers
- collects `tags` and `labels` for all assets (if available)
see [comment](https://github.com/elastic/security-team/issues/10435#issuecomment-2629356829)
- closes https://github.com/elastic/security-team/issues/10435
> Enrich GCP asset types with ECS fields

- deploy/asset-inventory-arm/install-agent-dev.sh
- deploy/asset-inventory-arm/install-agent.sh
- deploy/asset-inventory-cloudformation/elastic-agent-ec2-organization.yml
- deploy/asset-inventory-cloudformation/elastic-agent-ec2.yml
- deploy/azure/install-agent-dev.sh
- deploy/azure/install-agent.sh
- deploy/cloudformation/elastic-agent-ec2-cnvm.yml
- deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
- deploy/cloudformation/elastic-agent-ec2-cspm.yml
- deploy/deployment-manager/compute_engine.py
- tests/integration/tests/test_sanity_checks.py
> [!warning] 
> Do **not** backport this PR to 8.x
Adding `--install-servers` flag to deployment templates so that cloudbeat is installed in v9.x elastic-agent.
_1. Showcasing the new `elastic-agent install` flag in 9.x_
_2. Showing installed v9.0.0-beta1 agent_
Towards https://github.com/elastic/security-team/issues/11500
> Ensure cloudbeat is installed with >= 9.x elastic-agent

- deploy/azure/ARM-for-single-account.json
- deploy/azure/install-agent-dev.sh
- deploy/azure/install-agent.sh
This PR updates the `install-agent.sh` script to support installing Elastic Agent from both 8.x and 9.x versions.
- https://github.com/elastic/security-team/issues/11500
> Update install-agent.sh script

- deploy/asset-inventory-cloudformation/elastic-agent-ec2-organization.yml
- deploy/asset-inventory-cloudformation/elastic-agent-ec2.yml
- deploy/cloudformation/elastic-agent-ec2-cnvm.yml
- deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
- deploy/cloudformation/elastic-agent-ec2-cspm.yml
This PR updates the internal script to support Elastic Agent installation on both 8.x and 9.x versions.
> Fix CloudFormation templates to support installation on both 8.x and 9.x versions

- .github/workflows/test-gcp-dm.yml
This PR removes `github.actor` from the GCP label, as GCP deployment enforces strict labeling rules. Since `github.actor` can have unpredictable values, removing it reduces the risk of deployment failures like [there](https://github.com/elastic/cloudbeat/actions/runs/13410325369/job/37459503924).
> Update GCP label in GCP Deployment Manager workflow

- internal/inventory/azurefetcher/common.go
- internal/inventory/azurefetcher/fetcher_account.go
- internal/inventory/azurefetcher/fetcher_activedirectory.go
- internal/inventory/azurefetcher/fetcher_resource_graph.go
- internal/inventory/azurefetcher/fetcher_storage.go
This fixes missing resource names for some Storage services and Tenants.
_Before_
_After_
From 9.0 QA Cycle
> [Asset Inventory][Azure] Fix empty `entity.name` field for some resources

- .github/actions/elk-stack/action.yml
This PR fixes the Kibana links used for running UI sanity tests.
This [attempt](https://github.com/elastic/cloudbeat/actions/runs/13519520355/job/37775453787) confirms that UI tests were executed, with one test failing due to recent [UI changes](https://github.com/elastic/kibana/pull/207155), which will be addressed in a separate [fix](https://github.com/elastic/kibana/pull/212368).
Related Changes
- https://github.com/elastic/kibana/pull/212368
> Update workflow to fix running UI sanity tests.

- internal/config/config.go
- internal/config/config_test.go
- internal/flavors/benchmark/aws.go
- internal/flavors/benchmark/aws_org.go
- internal/flavors/benchmark/aws_test.go
- internal/resources/providers/awslib/config.go
- scripts/packaging/docker/elastic-agent/Dockerfile
Fixes: https://github.com/elastic/cloudbeat/issues/2556
> cloud connectors role chaining

- deploy/test-environments/modules/aws/eks/oidc.tf
This PR adds a new resource that checks the EKS cluster status and waits until the cluster becomes active.
[AWS docs reference](https://docs.aws.amazon.com/cli/latest/reference/eks/wait/cluster-active.html#description)
[Successful run](https://github.com/elastic/cloudbeat/actions/runs/13833462722/job/38702886455) after the fix.
> Fix EKS cluster deployment

- .github/workflows/test-e2e-flow.yml
Test-runner workflow is failing on the `run-serverless-main` job due to a deployment name that is too long. This PR shortens the deployment name to resolve the issue.
> Update deployment name

- .github/dependabot.yml
- .github/workflows/arm-template-lint.yml
- .github/workflows/ci-pull_request.yml
- .github/workflows/ci.yml
- .github/workflows/cloudformation-ci.yml
- .github/workflows/eks-ci.yml
- .github/workflows/packaging.yml
- .github/workflows/publish-cloudformation.yml
- .github/workflows/unit-test.yml
- .github/workflows/updatecli.yml
- dev-docs/Cloud-Env-Testing.md
This PR reflects the deprecation of the 8.x branch by updating all relevant files across the repository. The following changes are included:
- Removed any remaining references to 8.x.
- Replaced 8.x with 8.19, which is now the final branch for version 8.
> Update references from 8.x to 8.19 following branch deprecation

- internal/config/config.go
- internal/resources/providers/azurelib/auth/auth_provider.go
- internal/resources/providers/azurelib/auth/credentials.go
- internal/resources/providers/azurelib/auth/credentials_test.go
- internal/resources/providers/azurelib/auth/mock_azure_auth_provider_api.go
Enables https://github.com/elastic/cloudbeat/pull/3227 and https://github.com/elastic/cloudbeat/pull/3226 to be merged
> Remove Azure Username and Password authentication because it's deprecated on 1.9.0

- internal/config/config.go
- internal/config/config_test.go
- internal/flavors/assetinventory/strategy.go
- internal/flavors/benchmark/gcp.go
- internal/flavors/benchmark/gcp_test.go
- internal/resources/providers/gcplib/inventory/grpc_rate_limiter.go
- internal/resources/providers/gcplib/inventory/grpc_rate_limiter_test.go
- internal/resources/providers/gcplib/inventory/mock_provider_initializer_api.go
- internal/resources/providers/gcplib/inventory/provider.go
- internal/resources/providers/gcplib/inventory/provider_test.go
on gcp asset client:
* Increased the default timeout on `ListAssets` to 4 minutes (configurable).
* Increased the default page size to 200 (from 100) on `ListAssets` (configurable).
* Added overwrite functionality using env vars `CLOUDBEAT_GCP_LIST_ASSETS_PAGE_SIZE` and `CLOUDBEAT_GCP_LIST_ASSETS_TIMEOUT`.
* Created a wrapper on gax Retryer that logs on each retry.
> Increase gcp ListAssets timeout and page size

- .ci/updatecli/updatecli.d/update-beats.yml
See https://github.com/elastic/cloudbeat/actions/runs/15368849301/job/43245213040
```
ERROR: environment variable "GOPATH" not found, skipping
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29d1dfb]
```
In comparison, update-mods.yml does not export the `GOPATH` variable and still works: https://github.com/elastic/cloudbeat/blob/973858700dba3438417966d16ab7ead9b4875d73/.ci/updatecli/updatecli.d/update-mods.yml#L43-L44
> Attempt to fix update-beats.yml

- tests/integration/tests/test_standalone_agent_integration.py
This PR skips a test case that is currently flaky.
- Related: https://github.com/elastic/cloudbeat/issues/3372
> Skip flaky test case

- .github/workflows/bump-version.yml
`inputs.` automatically handles boolean types, while `github.event.inputs.` treats everything as strings.
The `if` was in that form `if: ${{ github.event.inputs.bump_integration }}` so it resulted in running always, no matter the boolean value of the input.
https://docs.github.com/en/actions/reference/accessing-contextual-information-about-workflow-runs#inputs-context
`github.event.inputs.` = Raw webhook data (strings only)
`inputs.` = Processed, typed data (respects boolean, choice, etc.)
> Fix bump-workflow boolean inputs

- .github/actions/cis-agentless/action.yml
- .github/workflows/test-environment.yml
- tests/integrations_setup/install_agentless_integrations.py
This pull request introduces support for a "serverless mode" configuration in the CIS Agentless Integrations setup. Key changes include updates to the action configuration, workflow files, and Python scripts to enable conditional behavior based on the serverless mode setting.
* [`.github/actions/cis-agentless/action.yml`](diffhunk://#diff-4e0c3e906c2958454508ddef8fc4ac83e0aa98279e4a5433f41c11e7d17855efR23-R26): Added a new input parameter `serverless-mode` with a default value of `"false"`. This parameter is passed to the environment during the action run. [[1]](diffhunk://#diff-4e0c3e906c2958454508ddef8fc4ac83e0aa98279e4a5433f41c11e7d17855efR23-R26) [[2]](diffhunk://#diff-4e0c3e906c2958454508ddef8fc4ac83e0aa98279e4a5433f41c11e7d17855efR40)
* …
> [Cloud Security] Fix agentless configuration for Serverless CreateEnvironment GH Actions

- .github/workflows/cdr-infra.yml
- .github/workflows/test-environment.yml
This PR exposes the expiration functionality, allowing the user to specify the number of days before the environment expires.
> Add expiration support to CDR wf

- .github/workflows/backport-active.yml
Support backports after a PR has been merged and labelled with `backport-active-*`.
Fixes a corner case when the PRs have been labeled after being merged with the supported list of active branches.
> github-actions: support backport labels after being merged

- .ci/scripts/gh-cache.sh
- .github/actions/hermit/action.yml
- .github/workflows/eks-ci.yml
- Removes caching used in eks-ci. Since that action runs only on the main branch, it doesn't affect developers as much as using our cache for PRs.
- Re-add restore-keys for hermit environment. This was deleted because of https://github.com/elastic/cloudbeat/issues/2446. However, we are cleaning the local hermit cache on cache misses, which should avoid constantly increasing our cache size.
- Re-use our hermit setup action in eks-ci, remove old go caching
> GH actions: Improve caching
